sonic-net/sonic-swss-common

common/select.cpp
common/select.h

common: add removeSelectable function in Select class

---

common/consumertable.cpp
common/producertable.cpp
tests/Makefile.am

Adding alterTable flag which will help to address db freeze scenario:
OA is restarting, but in the same time some APP decided to add/del some entries in app view, then after OA restarts, current app view could be altered (added/chanded/deleted entries) and also the same message is still in the producer queue which is not desired: for example event was to set entry, and OA will read the same operation again and execute it.
Also note: should this implemented behavior should be as default?

Consumer should populate table, not producer

---

common/Makefile.am
common/selectableevent.cpp
common/selectableevent.h
tests/Makefile.am
tests/redis_ut.cpp

Purpose of this class is to allow threads waiting on selectable objects to be notified by user if for example user wants to finish thread, instead of periodic cause timeouts and check if thread needs to end

Add SelectableEvent class

---

Makefile.am
configure.ac
get-gtest.sh
tests/Makefile.am

- Adding get-gtest.sh script
- Fixing Makefile.am and configure.ac

test: Fixing googletest build deps and scripts

---

common/table.cpp
common/table.h
tests/redis_ut.cpp

This function is used to retrieve the whole content of a table.
It will future be used for orchagent restarting logics.

table: Adding getTableContent function

---

common/json.h
common/producertable.cpp
common/producertable.h
tests/Makefile.am
tests/json_ut.cpp

- Use json.hpp to construct the JSON data and store into the m_dumpFile,
which could be used as input file for swssconfig.
- Add unit test for verification

producertable: Adding dump file to record all producer activities to file

---

common/notificationconsumer.cpp
common/notificationconsumer.h
common/select.cpp
tests/Makefile.am
tests/ntf_ut.cpp

In previous implementation on high volume of notifications on the stream messages were swallowed in readCache method, and previous "m_msg" was not populated, and since readCache returned DATA result, readMe method (which populates m_msg) was not called which was causing duplicated notifications poped. Now queue was introduced and populated every time we get valid redis reply, and pop is accessing queue directly.

Fix duplicated notifications bug

---

common/producerstatetable.cpp
common/rediscommand.h
tests/redis_state_ut.cpp

Fix #71: ProducerStateTable does not support field/value names with space characters

Fix #71: ProducerStateTable does not support field/value names with space characters

---

common/schema.h

Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

[schema]: Add VLAN_MEMBER_TABLE and LAG_MEMBER_TABLE

---

common/tokenize.cpp
common/tokenize.h
tests/tokenize_ut.cpp

This function is helpful when trying to tokenize a key-value string
that the tokenizer used between key and value also appears in value.
i.e. "neigh:00:00:00:00:00:00" and "NEIGH_TABLE:lo:fc00::79"

[tokenize]: Add tokenizeFirst function

---

common/consumerstatetable.cpp
common/consumerstatetable.h
common/consumertable.cpp
common/consumertable.h
common/table.h

- By default, the pop batch size is 128. It could be set to other
values when necessary. If a value large enough is set here, the
behavior will be to pop out all existing items in the table.

[ConsumerTable]: Set pop batch size as a constructor parameter

---

common/Makefile.am
configure.ac

Change include of libnl to work with sysroot option, use correct
variables for flags.
Signed-off-by: marian-pritsak <marianp@mellanox.com>

Fix flags in makefiles

---

common/netlink.cpp

When we're add many neighbors to our database, we can lose some netlink messages. In this case our app_db database doesn't have all neighbor entries in comparison with Linux kernel.
This pull request introduce a quick fix. It's better to have two threads for the code. One thread for reading data from the socket, another one for writing to database.

Increase netlink buffer. Otherwise we're loosing netlink messages

---

common/netlink.cpp

When our library is not fast enough in reading netlink messages we're loosing them.
Report about such cases in the log

[netlink]: Check return code from nl_recvmsgs_default to catch lost messages

---

common/select.cpp
common/selectableevent.cpp

We need to handle EINTR error returning from UNIX API calls.
When we receive a signal a UNIX API call can return EINTR which is not error.
We have to restart an UNIX API call when it returns EINTR.
Otherwise we see this in our log and orchagent crashes.
"NOTICE orchagent: :- start: Error: Interrupted system call!"
We also can solve the issue with a MACRO:
```
#define HANDLE_EINTR(x) ({ \
typeof(x) __eintr_result__; \
do { \
__eintr_result__ = (x); \
} while (__eintr_result__ == -1 && errno == EINTR); \
__eintr_result__;\
```

[Selectable]: EINTR error handling

---

common/Makefile.am

GNU Automake does not support wildcards, which makes the build fail on
some versions of Automake with error "No rule to make target *.lua".
Signed-off-by: marian-pritsak <marianp@mellanox.com>

[Makefile.am]: Use full file names

---

common/schema.h

CONFIG_DB and PFC_WD_DB used same DB index
Now they are split to 5 and 4

[schema]: Fix DB indeces

---

common/netlink.cpp

As recommended at http://www.infradead.org/~tgr/libnl/doc/core.html : If a socket is used to only receive notifications it usually is best to put the socket in non-blocking mode and periodically poll for new notifications.
Also due to the incorrect setting of NLM_F_MULTI flag in some netlink messages, netlink process got stuck in "static int recvmsgs(struct nl_sock *sk, struct nl_cb *cb)" function of libnl if a socket is in blocking mode.
4.x kernel has fix to the wrong use of NLM_F_MULTI problem: github.com/torvalds/linux/commit/46c264daaaa569e24f8aba877d0fd8167c42a9a4 but introducing the fix to 3.16 will break Debian Jessie ABI. Setting netlink socket to non-blocking mode to get around the problem without kernel change.

Change netlink socket to non-blocking mode by default.

---

common/Makefile.am
common/exec.cpp
common/exec.h
tests/Makefile.am
tests/exec_ut.cpp

Add support for executing shell command in c++ code.
jipan@043cf76fe4fe:/sonic/src/sonic-swss-common/tests$ ./tests --gtest_filter=EXEC*
Running main() from gtest_main.cc
Note: Google Test filter = EXEC*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from EXEC
[ RUN      ] EXEC.result
[       OK ] EXEC.result (6 ms)
[ RUN      ] EXEC.error
[       OK ] EXEC.error (2 ms)
[----------] 2 tests from EXEC (8 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (8 ms total)
[  PASSED  ] 2 tests.
jipan@043cf76fe4fe:/sonic/src/sonic-swss-common/tests$ ./tests --gtest_filter=EXEC*
Running main() from gtest_main.cc
Note: Google Test filter = EXEC*
[==========] Running 2 tests from 1 test …

Add exec library for executing shell commands

---

common/exec.cpp

Clear stdout string before filling it with command output, so the stdout is guaranteed to hold clean result and doesn't reply on user to clean it explicitly.  It is convenient when application wants run exec multiple times in a function.
jipan@ea03d6710aec:/sonic/src/sonic-swss-common$ tests/tests --gtest_filter=EXEC 
Running main() from gtest_main.cc
Note: Google Test filter = EXEC*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from EXEC
[ RUN      ] EXEC.result
[       OK ] EXEC.result (5 ms)
[ RUN      ] EXEC.error
[       OK ] EXEC.error (1 ms)
[----------] 2 tests from EXEC (6 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 …

Clear stdout string before filling it with command output

---

common/logger.cpp
common/logger.h

The Logger priority thread was not gracefully detached. This would
cause `terminate called without an active exception` after the main
program exits.
Add related unit test to check if the program exits successfully with
or without the thread exists.

[logger]: Add destructor to detach Logger priority thread

---

common/schema.h
common/table.cpp
common/table.h
tests/redis_ut.cpp

Default separator is :
Application may choose different table separator like "|" when creating table or using tableBase 
jipan@ea03d6710aec:/sonic/src/sonic-swss-common$ tests/tests                     
Running main() from gtest_main.cc
[==========] Running 49 tests from 14 test cases.
[----------] Global test environment set-up.
[----------] 8 tests from DBConnector
[ RUN      ] DBConnector.test
Starting 128 producers and consumers on redis
+++++-+-+-++Done. Waiting for all job to finish 1000 jobs.
+++++--+++++++++++++-+++++++++++++---+++++---++++++++++++-++++++++++++-+-+-++++++-++++-++++++-+++++++++++-+-+++-+-+++-++++++++++++++++-++++-+++++++-+-+-++++++++++++-++++-+++++++++++-+++++++++++++--+-+-+++++-+-+++++++-+++++++-+-+-+++++++++++ …

Support specifying table name separator for table and tableBase class.

---

common/schema.h

Add stateDB table name for lag and vlan

---

common/schema.h

Add configDB table names to schema.h

---

common/producerstatetable.cpp
common/rediscommand.h
common/table.cpp
common/table.h

prepare to introduce swig support since swig does not support std::tuple

use std::pair instead of std::tuple for FieldValueTuple

---

common/Makefile.am
common/timestamp.cpp
common/timestamp.h

This is to move the getTimestamp() function defined in swss saihelper.cpp and sai_redis_record.cpp to swss-common to avoid duplications.   No change to the function code itself.
Users of getTimestamp() also include Orch class in swss.

Add getTimestamp() common function

---

pyext/swsscommon.i
tests/test_redis_ut.py

```
lgh@ddf90f25c0d1:/data/sonic/sonic-swss-common$ py.test tests/
================================================== test session starts ===================================================
platform linux2 -- Python 2.7.9 -- py-1.4.25 -- pytest-2.6.3
plugins: cov
collected 2 items 
tests/test_redis_ut.py ..
================================================ 2 passed in 0.04 seconds ================================================
```

add support for SubscriberStateTable in python library

---

common/schema.h

I've added table identifier for one more state table: VLAN_MEMBER.
I need them to improve current Fast-Reboot procedure, by applying saved FDB and ARP entries right after a VLAN_MEMBER interface was added.

Add VLAN_MEMBER state table

---

common/linkcache.cpp
common/linkcache.h

Signed-off-by: Haiyang Zheng <haiyang.z@alibaba-inc.com>
Add getLinkByName() function which will be used by intfsyncd to get the link attributes (such as MTU) by name

[linkcache]: Add getLinkByName() function

---

common/table.cpp
tests/redis_ut.cpp

When table name has separator, e.g., ASIC_DB:ROUTE and
the table name separator is ':'. getKeys will return ROUTE:key
instead of key.

[table]: return correct key when table name has separator

---

common/ipprefix.h
tests/ipprefix_ut.cpp

API to return broadcast IP for any given subnet. 
Why I did this?
For subnet-directed IPv4 broadcast packets to be routed in data-plane, an entry has to be added in the layer 3 tables with the destination as the broadcast IP of the subnet. This feature is waiting on SAI support. 
**Note:** 
Subnet directed broadcast is not supported in IPv6 and hence this API is meaningful only for the IPv4 address family. However, the API to be in sync with the python class `ipaddress.IPv6Network.broadcast_address`, support is added to get broadcast address for IPv6 as well.
Please review the UT section for examples.

API to return broadcast IP

---

common/macaddress.cpp
common/macaddress.h
tests/macaddress_ut.cpp

MacAddress class instantiated many times from string. Also we parse mac addresses a lot. I did a benchmark and I found that our old version of to_string() and parseMacString() methods not so fast.
I've rewritten both of them. Now both methods faster (parseMacString - 76 times faster, almost 10 times faster) and parseMacString() catch more errors.
```
2018-01-03 23:01:53
Run on (16 X 2394.44 MHz CPU s)
CPU Caches:
L1 Data 32K (x16)
L1 Instruction 32K (x16)
L2 Unified 256K (x16)
L3 Unified 30720K (x16)
------------------------------------------------------------
Benchmark                     Time           CPU Iterations
------------------------------------------------------------
BM_ParseMacOld              840 ns        840 ns     842880
BM_ParseMac                  11 ns         11 ns …
```

[MacAddress]: Optimize to_string() and parseMacString methods

---

common/macaddress.cpp
common/macaddress.h
tests/Makefile.am

1. Remove code from stackoverflow which was introduces by https://github.com/Azure/sonic-swss-common/pull/171
2. Convert tabs to spaces

[MacAddress]: Remove code from stackoverflow

---

common/redisclient.h
pyext/swsscommon.i

Required for pyext to get access to VIDTORID table

Add RedisClient to pyext

---

common/redisclient.h
pyext/swsscommon.i

Reverts Azure/sonic-swss-common#176

Revert "Add RedisClient to pyext"

---

common/ipprefix.h
tests/ipprefix_ut.cpp

This method is being currently utilized by the new interface's overlapping-detection logic (to be submitted under a different PR within sonic-swss repo). Method's goal is to simply return the subnet associated to any given prefix (see example below). A new pytest testcase will be appended shortly.
Examples:
subnet("10.1.1.1/24") = 10.1.1.0/24
subnet("fc00:0003:0002:0002::2/64") = fc00:0003:0002:0002:0000:0000:0000:0000/64

Extending IpPrefix class to return the subnet associated to any given prefix

---

common/ipaddress.cpp
common/ipaddress.h
tests/ipaddress_ut.cpp

This code is required by link-local functionality (sonic-swss PR/437).
UTs execution:
rmolina@6175c07b92ba:/sonic/src/sonic-swss-common$ sudo ./tests/tests
...
[----------] 2 tests from IpAddresses
[ RUN      ] IpAddresses.empty
[       OK ] IpAddresses.empty (0 ms)
[ RUN      ] IpAddresses.contains
[       OK ] IpAddresses.contains (1 ms)
[----------] 2 tests from IpAddresses (1 ms total)
[----------] 1 test from IpAddress
[ RUN      ] IpAddress.getAddrScope
[       OK ] IpAddress.getAddrScope (0 ms)
[----------] 1 test from IpAddress (0 ms total)
...

Extending IpAddress class with method to return the scope of any given ip-address

---

common/logger.cpp

Fix a bug introduced by https://github.com/Azure/sonic-swss-common/pull/186
Without the patch you can see following output. The SAI subsystem log levels weren't initialized:
```
ERR syncd: :- get_enum_value_from_name: not found SAI_API_SWITCH:SAI_API_SWITCH
ERR syncd: :- get_enum_value_from_name: not found SAI_API_PORT:SAI_API_PORT
ERR syncd: :- get_enum_value_from_name: not found SAI_API_FDB:SAI_API_FDB
ERR syncd: :- get_enum_value_from_name: not found SAI_API_VLAN:SAI_API_VLAN
ERR syncd: :- get_enum_value_from_name: not found SAI_API_VIRTUAL_ROUTER:SAI_API_VIRTUAL_ROUTER
ERR syncd: :- get_enum_value_from_name: not found SAI_API_ROUTE:SAI_API_ROUTE
ERR syncd: :- get_enum_value_from_name: not found SAI_API_NEXT_HOP:SAI_API_NEXT_HOP
ERR syncd: :- get_enum_value_from_name: not found …
```

Fix a bug which caused SAI use unintialized log levels

---

common/consumertablebase.cpp
common/dbconnector.cpp
common/dbconnector.h
common/notificationconsumer.cpp
common/producerstatetable.cpp
common/producertable.cpp
common/redispipeline.h
common/schema.h
common/subscriberstatetable.cpp
common/table.cpp
common/table.h
tests/redis_piped_ut.cpp
tests/redis_subscriber_state_ut.cpp
tests/redis_ut.cpp
tests/test_redis_ut.py

Previously, SubscriberStateTable was hardcoded to use `CONFIGDB_TABLE_NAME_SEPARATOR`, which meant that one could only subscribe to notifications from databases which used "|" as a table name separator. If you subscribed to a database which used ":" as a table name separator, you would never receive notifications.
This change creates a constant map of database ID to table name separator, and chooses the appropriate table name separator for a table based on the DB one is connecting to. While fixing the above problem, I also simplified the method calls for instantiating Table objects, as one no longer needs to pass in the table separator. This will also prevent table name separator mismatches in the future.
Also changed name of `DEFAULT_TABLE_NAME_SEPARATOR` to `LEGACY_TABLE_NAME_SEPARATOR` …

Add map of database ID -> table name separator; No longer pass table name separator when constructing Table objects

---

tests/json_ut.cpp
tests/redis_piped_state_ut.cpp
tests/redis_piped_ut.cpp
tests/redis_state_ut.cpp
tests/redis_subscriber_state_ut.cpp

- Align (almost) all unit tests with new definition of TEST_DB (ID 15). Exceptions include redis_state_ut.cpp and redis_piped_state_ut.cpp, which now test against APPL_DB (DB ID 0), because due to hardcoded colon (":") separators in consumer_table_pops.lua, ConsumerTable/ConsumerStateTable currently only work with tables which use the colon as a table name separator.
- Remove hard-coded table name separators from json_ut.cpp. Instead, fetch separator from Table object

Make C++ Unit Tests work with recent table name separator changes

---

common/logger.h
tests/json_ut.cpp
tests/redis_piped_ut.cpp
tests/redis_ut.cpp

Compiling with gcc-7, two errors occurred:
Firstly, an include was missing (commit 5127067) and secondly the compiler was complaining about dangling else ambiguity in tests (commit 0d407f0) when EXPECT_xx was used in if-conditions without surrounding brackets.

Fix compiler errors with gcc-7

---

common/consumer_table_pops.lua
common/consumertable.cpp
common/producertable.cpp
common/table.h

This is to combine the three separate operations for key, op and value into one operation.
With swssconfig to load route to appDB and trigger route download to ASIC, the overall loading speed increased 5~10% in multiple rounds of test.   Don't have the direct speed improvement number for producer/consumer channel only,  it should be better than that number.
Since the change is pretty straight forward and simple, and the improvement is obvious, please consider merging this change.

Reduce the number of LPUSH/LRANGE/LTRIM operations for producer/consumer

---

common/consumer_table_pops.lua
common/consumertable.cpp
common/producertable.cpp
common/table.h
tests/redis_ut.cpp

This is a redo of https://github.com/Azure/sonic-swss-common/pull/203, fixed the problem of wrong m_queueLength for ConsumerTable constructor when there is data available before consumer is created.
Test case ConsumerSelectWithInitData added to swss-common unit test to cover this scenario.
Passed sonic-sairedis and swss-common unit test.
brcm.pl 
```
root@7ab17491ef82:/sonic/src/sonic-sairedis/tests# ./brcm.pl 
Using scripts dir 'brcm'
main::test_brcm_start_empty: Fresh start
Killing syncd
.......
Starting syncd
Replay full_no_queue_no_ipg_no_buffer_pfofile.rec
WARN: sai_metadata_apis_query: :- failed to query api SAI_API_IPMC: SAI_STATUS_INVALID_PARAMETER (-5)WARN: sai_metadata_apis_query: :- failed to query api SAI_API_IPMC_GROUP: SAI_STATUS_INVALID_PARAMETER (-5)WARN: …
```

One lrange and test, Reduce the number of LPUSH/LRANGE/LTRIM operations for producer/consumer

---

common/consumer_state_table_pops.lua
common/consumerstatetable.cpp
common/producerstatetable.cpp
common/table.h
tests/redis_state_ut.cpp

Original implementation will have 2 issues:
1. The consumer side will accumulate all the state into redis hashes, and each time a new field/value, the consumer will pop it, and return all the filed/value accumulated.
2. The producer side modify the redis hashes directly. To behavior the same way as Producer/ConsumerTable, let the consumer side modify the redis hashes.

Improve ConsumerStateTable: del after consumed, and let consumer writes the final table

---

common/select.cpp
common/select.h
tests/redis_subscriber_state_ut.cpp

For warm restart state restore,  there is need to check if all cached selectables have been processed.

Warm reboot: Add support for bool Select::hasCachedSelectable()

---

common/producertable.cpp

* create operation is used when writing routes into ASIC_DB
* operation create is added to make sure 'create' cases are redis pipelined
* with the changes in sairedis and swss, route performance improved by 200~300 routes/sec

swss-common: add op 'create' case to avoid flush immediately

---

common/warm_restart.cpp
common/warm_restart.h
pyext/swsscommon.i
tests/warm_restart_ut.cpp

Add system warm-reboot check in WarmRestart class
UT test is also updated
Add the WarmRestart Class to python binding

Add system warm-reboot check in WarmRestart class

---

tests/redis_piped_state_ut.cpp
tests/redis_state_ut.cpp
tests/redis_subscriber_state_ut.cpp

since ios has explicit operator bool, we need to explicitly convert it to bool
see compilation error under ubuntu 16.04
```
g++ -DHAVE_CONFIG_H -I. -I.. -I .. -g -DNDEBUG  -ansi -fPIC -std=c++11 -Wall -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Werror -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wno-write-strings -Wno-missing-format-attribute -Wno-long-long …
```

[ut]: explicit convert is to bool type

---

common/Makefile.am
common/producer_state_table_apply_view.lua
common/producerstatetable.cpp
common/producerstatetable.h
common/table.cpp
common/table_dump.lua
tests/redis_state_ut.cpp

See detail in design doc: https://github.com/Azure/SONiC/blob/master/doc/warm-reboot/view_switch.md

Add ProducerStateTable temp view implementation and UT

---

common/schema.h

**Note: `CFG_VRF_TABLE_NAME`  is already defined in line 125**

Add NEIGH_TABLE to configDB for neighbor configuration

---

common/warm_restart.h

The default docker name caused a lot of confusion when the libraries used in other dockers

Remove default docker name value of swss.

---

common/selectableevent.cpp
common/selectabletimer.cpp

Update SelectableEvent and SelectableTimer throw message when
read failed.

[selectable]: Update throw message

---

pyext/swsscommon.i

enable types in stdint.h
e.g. uint32_t
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[pyext] enable types in stdint.h

---

common/redisclient.cpp
common/redisclient.h
common/rediscommand.cpp
common/rediscommand.h
tests/redis_ut.cpp

Add multiple fields hdel support
$ ./tests/tests --gtest_filter=DBConnector.RedisClient      
Running main() from gtest_main.cc
Note: Google Test filter = DBConnector.RedisClient
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DBConnector
[ RUN      ] DBConnector.RedisClient
Starting table manipulations
- Step 1. SET
Set key [a] field_1:1 field_2:2 field_3:3
Set key [b] field_1:1 field_2:2 field_3:3
- Step 2. GET_TABLE_KEYS
Get key [b]Get key [a]- Step 3. GET_TABLE_CONTENT
Get key [b] field_3:3 field_2:2 field_1:1
Get key [a] field_3:3 field_2:2 field_1:1
- Step 4. HDEL single field
Delete field_2 under key [a]
field_3:3 field_1:1
- Step 5. DEL
Delete key [a]
- Step 6. GET
Get key [a] and key [b]
Get key [b] field_3:3 …

Add multiple fields hdel support

---

common/schema.h

* VNET_ROUTE
* VNET_ROUTE_TUNNEL

[schema] Add VNET Route tables in config_db

---

common/logger.cpp
common/logger.h
common/selectabletimer.cpp

Upon failure to read timer_fd, do an assert instead of throw.
This way, the core can be obtained at the point of failure, instead of silent process termination.

Add an assert to logger, which will log a message and abort.

---

common/selectabletimer.cpp

Work around a kernel bug, where read(timerfd, ...) return code can be 0,
with errno = 0 as proper timer expiry.
Current code, though set it as CLOCK_REALTIME, since we set relative timestamp
for initial expiry & interval, the kernel handles it as MONOTONIC.
So this fix, does not affect any functionality, but just makes it explicit.

do not abort when read timerfd return 0 and errno = 0

---

common/schema.h

Add BGP_STATE_TABLE in stateDB for storing BGP related states.
Three PRs for adding BGP eoiu support to speed up route reconciliation in fpmsyncd
sonic-buildimage:  https://github.com/Azure/sonic-buildimage/pull/2823
sonic-swss-common: https://github.com/Azure/sonic-swss-common/pull/273
sonic-swss:  https://github.com/Azure/sonic-swss/pull/856

Add BGP_STATE_TABLE in stateDB

---

common/ipaddress.cpp
common/ipaddress.h
common/ipprefix.h
tests/ipaddress_ut.cpp
tests/ipprefix_ut.cpp

1. add mcast scope on IpAddress class
2. add isFullMask method on IpPrefix class

[IpAddress]: add mcast scope on address and isFullMask method on prefix

---

common/logger.cpp
common/logger.h
common/selectabletimer.cpp

* Add an assert to logger, which will log a message and abort.
Upon failure to read timer_fd, do an assert instead of throw.
This way, the core can be obtained at the point of failure, instead of silent process termination.
* Comments corrected per review comments.
* Changes per comments; No logical code changes.
* s/ASSERT/ABORT_IF_NOT/ per review comments.
* Initialize counter, so when we fail and get core, we could assess, if it was written to or not.
* Made it better per review comments. No logical change in code.

Add an assert to logger, which will log a message and abort. (#286)

---

common/selectabletimer.cpp

The return value of 0, with errno=0 is treated as benign, as this appears to be a Hardware related kernel bug.
NOTE: This bug is found to occur in S6100 platforms only.

timerfd:read failure - Record in logs as error.

---

common/netlink.cpp
common/netlink.h
common/notificationconsumer.cpp
common/notificationconsumer.h
common/redisselect.cpp
common/redisselect.h
common/selectable.h
common/selectableevent.cpp
common/selectableevent.h
common/selectabletimer.cpp
common/selectabletimer.h
common/subscriberstatetable.cpp
common/subscriberstatetable.h

timerfd read is expected to return 8 or for any other value appropriate
non-zero errno is expected. But due to a kernel bug, that is found to
occur in S6100 platform, there could be a return value of 0, with errno=0.
Per DELL, this implies timer fired but not forwarded, so take it as
false alarm, and next immediate read is expected to succeed.
Made the fix to meet it.

timerfd return 0 with errno =0 -  handle as False alarm.

---

common/consumer_table_pops.lua

* consumer_table_pops.lua added bulkremove option which will DEL redis DB entries
* this change is along with changes in sonic-sairedis , 
https://github.com/Azure/sonic-sairedis/pull/516

add bulkremove for consumer_table_pops.lua

---

common/netlink.cpp
common/netlink.h
common/notificationconsumer.cpp
common/notificationconsumer.h
common/redisselect.cpp
common/redisselect.h
common/selectable.h
common/selectableevent.cpp
common/selectableevent.h
common/selectabletimer.cpp
common/selectabletimer.h
common/subscriberstatetable.cpp
common/subscriberstatetable.h

Due to conflict, a separate PR Is created.
Ref: https://github.com/Azure/sonic-swss-common/pull/302

timerfd fix: Pass false alarm to caller.

---

common/consumerstatetable.cpp
common/consumerstatetable.h
common/consumertable.cpp
common/consumertable.h
common/dbconnector.cpp
common/dbconnector.h
common/logger.cpp
common/loglevel.cpp
common/schema.h
common/table.cpp
common/table.h
tests/Makefile.am
tests/redis_multi_db_ut.cpp
tests/redis_multi_db_ut_config/database_config.json

* add a new RedisConfig class which has static member and func, to parse/store/update/get database info from database_config.json file.
* add new DBConnector() constructor without port and unixsocket parameters. using RedisConfig class get func to get those info dynamically, all other DBConnector logic are same.
* the previous static sha member in tables are not good for multi-db cases, since on each db instance, there should be a SHA value, we cannot reuse only one SHA value, hence remove  the static keyword and keep SHA value as a member for each DBConnector object
* add updateDBConfigFile() to support vs test/ swsscommon test cases where this is no database_config.json at init time, we can point to load the config file.
* adding swsscommon unit test to check the  updateDBConfigFile() …

multi-DB Part 2: C++ interface API changes / swsscommon unit test / LOGLEVEL_DB apply new API

---

common/logger.cpp
common/loglevel.cpp

* Last multiDB commit, We tried to replace old DBConnector API with  new DBConnector API in logger/loglevel feature, this is fine on DUT  
* In vs Docker, it has no database_config.json file at /var/run/redis/sonic-db/, so all processes which are using logger/loglevel cannot connect to a DB, which cause VS test init failed
* the fix is to still use the old DBConnector API until the vs docker/testcase are modified based on the multiDB changes
* The lessons learnt :  please don't do the replacement between new API and old API at this moment, we need to add these new interfaces first and then do the vs test cases modification, and then do the replacement.
Below is vs test results:
dzhang@dzhang:~/MS_VS/sonic-buildimage/src/sonic-swss/tests$ sudo pytest -v
[sudo] password for dzhang: …

fix vs test, should NOT replace old DBConnector API with new DBConnector API at this moment

---

common/consumer_table_pops.lua

[consumer_table] Add messages for performing object availability query
* Specifies a request/response message pair for sai_object_type_get_availability
Signed-off-by: Danny Allen <daall@microsoft.com>
Related to: https://github.com/Azure/sonic-sairedis/pull/528

[consumer_table] Add messages for performing object availability query

---

common/logger.cpp
common/loglevel.cpp

Reverts Azure/sonic-swss-common#316
sairedis is using logger.cpp, and it was broken in runtime.

Revert "[MultiDB]: apply new APIs in swss-common"

---

common/dbconnector.cpp
tests/redis_multi_db_ut.cpp

* throwing exception if config file is missing
* using interface .at() to get map entry

[MultiDB]: throwing exception when database_config.json doesn't exist

---

common/Makefile.am
common/database_config.json
debian/libswsscommon.install
debian/postinst

* distribute  database_config.json into /var/run/redis/sonic-db/ when installing libswsscommon.deb in postinst script

[MultiDB]: install default db config file when installing libswsscommon if there is no such a file

---

common/logger.cpp
common/loglevel.cpp
common/warm_restart.cpp
common/warm_restart.h
tests/Makefile.am
tests/json_ut.cpp
tests/main.cpp
tests/ntf_ut.cpp
tests/redis_multi_db_ut.cpp
tests/redis_multi_db_ut_config/database_config.json
tests/redis_piped_state_ut.cpp
tests/redis_piped_ut.cpp
tests/redis_state_ut.cpp
tests/redis_subscriber_state_ut.cpp
tests/redis_ut.cpp
tests/selectable_priority.cpp
tests/test_redis_ut.py
tests/warm_restart_ut.cpp

* replacing swsscommon old APIs with new APIs, including logger, WarmStart and Unit tests
* redisign WarmStart::init() signature, reuse new DBConnector API flag to choose SOCKET or TCP connection.
* unit test adding main() entry function to run multiDB tests first which will init all the db config data once, all other tests will reuse these data.
* update db config file to the latest version which include the separator.
* VS tests all passed.
* swsscommon UT all passed. 

[MultiDB]:swsscommon replace old API with new APIs including tests

---

tests/macaddress_ut.cpp

To solve error when run `dpkg-buildpackage -us -uc -b`
```
In file included from /usr/include/gtest/gtest.h:57:0,
from macaddress_ut.cpp:2:
macaddress_ut.cpp: In member function ‘virtual void MacAddress_parse_Test::TestBody()’:
macaddress_ut.cpp:64:48: error: ‘invalid_argument’ does not name a type
EXPECT_THROW(MacAddress("52:54:00:25:E9"), invalid_argument);
^
macaddress_ut.cpp:64:5: error: expected ‘)’ before ‘const’
EXPECT_THROW(MacAddress("52:54:00:25:E9"), invalid_argument);
^
macaddress_ut.cpp:64:5: error: expected ‘{’ before ‘const’
macaddress_ut.cpp:64:5: error: expected unqualified-id before ‘)’ token
EXPECT_THROW(MacAddress("52:54:00:25:E9"), invalid_argument);
^
macaddress_ut.cpp:64:5: error: expected initializer before ‘)’ token
macaddress_ut.cpp:64:5: error: expected …
```

Add stdexcept lib to solve error when build pkdg

---

common/dbconnector.cpp
common/dbconnector.h
tests/redis_ut.cpp
tests/test_redis_ut.py

Add `setClientName()` and `getClientName()` methods to DBConnector class to allow for assigning a name to the client in Redis, which is helpful when debugging Redis clients using `redis-cli client list`.

[DBConnector] Add methods to set/get Redis client name

---

common/consumertablebase.cpp
common/dbconnector.cpp
common/dbconnector.h
common/producerstatetable.cpp
common/redispipeline.h
common/table.cpp
tests/redis_ut.cpp

If DBConnector is constructed by a dbId, there is no dbName at all. We need to get a separator from the dbId. And the mapping is get from database_config.json.
The bug was introduced by https://github.com/Azure/sonic-swss-common/pull/336

Fix backward compatible for a DBConnector without a dbName

---

pyext/Makefile.am
pyext/swsscommon.i
tests/test_redis_ut.py

We have a memory leak in pyext. As result ledd, lddpd, and pmon could use a lot of memory.
I was able to extract the memory leak patter in the following testcase:
You need to have pympler package installed.
```
from swsscommon import swsscommon
from pympler.tracker import SummaryTracker
def main():
tracker = SummaryTracker()
appl_db = swsscommon.DBConnector(0, "localhost", 6379, 0)
sel = swsscommon.Select()
sst = swsscommon.SubscriberStateTable(appl_db, "TABLE")
sel.addSelectable(sst)
for _ in xrange(10000):
state, c = sel.select(1000)
tracker.print_diff()
main()
```
With the following client code
client.py
```
from swsscommon import swsscommon
app_db = swsscommon.DBConnector(swsscommon.APPL_DB, "localhost", 6379, 0)
t = swsscommon.Table(app_db, "TABLE")
def z(t, st):
fvs = …
```

Fix memory leak in pyext when Selectable is returned to Python

---

common/schema.h

According to [HLD](https://github.com/Azure/SONiC/blob/ec6d35dd2c28491bfade19cfee990fe612f1e5e9/doc/rates-and-utilization/Rates_and_utilization_HLD.md)
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

[schema] update schema with rates and utilization table names

---

common/loglevel.cpp

We have an issue [4338 swssloglevel -p crashes](https://github.com/Azure/sonic-buildimage/issues/4338). Looks like the story is like this: someone inserts the log level entries through `ProductionStateTable` but nobody tries consuming those entries, leaving the keys of most of the entries prefixed with an underscore and failing the `swssloglevel` who doesn't try to handle this case.
This PR put a check in the `swssloglevel` as a WA.
On top of that, it's still necessary to find out who is responsible to consume the entries in the database and why it doesn't do that.

[loglevel] Avoid accessing null ptr in swssloglevel

---

tests/fdb_flush.cpp

Compilation Warnings: fprmat specifier of size 32 bit but argument is of
size 64bit
Fix: Use PRIxy inittypes printf format specifiers
Signed-off-by: Antony Rheneus <arheneus@marvell.com>

[sonic-swss-common] ARMHF warning fixes

---

m4/python3.m4

sysconfig is added in Python3.2
distutils.sysconfig is from Python2
Python3.6 does not support distutils.sysconfig

use sysconfig instead of distutils.sysconfig

---

tests/test_redis_ut.py

```
lgh@jenkins-worker-17:~/sonic-swss-common/tests$ py.test -v  
======================================== test session starts ========================================
platform linux -- Python 3.8.2, pytest-4.6.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/lgh/sonic-swss-common/tests
plugins: flaky-3.6.1
collected 7 items                                                                                   
test_redis_ut.py::test_ProducerTable PASSED                                                   [ 14%]
test_redis_ut.py::test_ProducerStateTable PASSED                                              [ 28%]
test_redis_ut.py::test_Table PASSED                                                           [ 42%]
test_redis_ut.py::test_SubscriberStateTable …
```

fix pytest for python3

---

common/logger.cpp
tests/Makefile.am
tests/logger_ut.cpp

- Why I did it
This PR contains the code changes to fix the SAI API log level issue Azure/sonic-swss-common#366
- Why this issue happens
In the initialization of syncd, the main function first calls linkToDbNative function to initialize the log level for syncd. Then the log levels for SAI APIs are initialized using linkToDb. Since the settingThread of logger is set up by linkToDbNative function and the ConsumerStateTables are set up only in the initialization of the thread, the SAI API log levels in only added to m_settingChangeObservers, whereas the corresponding ConsumerStateTables are not created. Therefore, the SAI API log levels are not successfully initialized.
- How I did it
Instead of creating ConsumerStateTables at the initialization of settingThread, I create ConsumerStateTables …

Fix sai api loglevel

---

common/dbconnector.cpp
common/dbconnector.h
common/redisselect.cpp
common/redisselect.h
common/selectable.h
tests/Makefile.am
tests/main.cpp
tests/redis_multi_db_ut_config/database_config0.json
tests/redis_multi_db_ut_config/database_config1.json
tests/redis_multi_db_ut_config/database_global.json
tests/redis_multi_ns_ut.cpp

Why:
The dbconnector classes here need to understand the namespace, to connect to redis databases running in database containers in different linux network namespaces in case of multi-asic platforms.
What:
The class data structures are modified to handle the new dimension of namespace. New api's are added to parse the database_global.json file and to retrieve the list of namespaces + parse the respective database_config.json file. The namespaces will be ""(default namespace for the linux host) and "asic0", "aisic1" .... as present in the /var/run/redis/sonic-db/database_global.json file.
How verified:
Verification was done on a multi-asic platform with pmon scripts which uses swsscommon dbconnector classes.
**Note** : testcases to be updated, in this or in a follow up PR.

DBConnector classes to understand the namespace.

---

common/dbconnector.cpp
common/dbconnector.h
common/redisselect.cpp
common/redisselect.h
common/selectable.h
tests/Makefile.am
tests/main.cpp
tests/redis_multi_db_ut_config/database_config0.json
tests/redis_multi_db_ut_config/database_config1.json
tests/redis_multi_db_ut_config/database_global.json
tests/redis_multi_ns_ut.cpp

Adding PR #364 back. 
It was reverted earlier as there was a build failure with **sonic-swss/tests/mock_tests/mock_dbconnector.cpp** failing to build due to DBConnnector constructor being redefined there (Issue mentioned in https://github.com/Azure/sonic-swss/issues/1363). 
I have addressed it now by keeping the old constructor and delegating that to the new constructor which has "namespace" as additional argument.
This PR, I have included the changes to further align the dbConnector class here in sonic-swss-common with one present in sonic-py-swssdk
1. Ignore ( don't throw exception ) if the database_global.json file is not present.
2. validate the namespace before using it.

Reintroducing PR #364 - DBconnector to support namespaces.

---

common/dbconnector.cpp
common/dbconnector.h
common/redisselect.cpp
common/redisselect.h
common/selectable.h
tests/Makefile.am
tests/main.cpp
tests/redis_multi_db_ut_config/database_config0.json
tests/redis_multi_db_ut_config/database_config1.json
tests/redis_multi_db_ut_config/database_global.json
tests/redis_multi_ns_ut.cpp
tests/redis_ut.cpp

Why:
The commit for support for namespaces in DBConnector (#371) class was reverted earlier as it failed couple of tests in swss. It was found that the SWSS docker virtual switch API's create the DBConnector object using the constructor API's which was present before the multi-DB changes went in. During those times, the DBConnector classes used dbId alone and dbName was not filled. (https://github.com/Azure/sonic-swss/blob/eac1d898e12d03040cd7b4e3c4059960dbf0ae8d/tests/dvslib/dvs_database.py#L30)
The reason for the tests failure was because the dbName was coming as NULL when we try to create newConnector().
What:
Added the check to see if the dbName, namespace is empty, if so create the DBConnector using the old constructors which takes dbId as input. If not call the new constructor where …

Dbconnector namespace support

---

common/redisselect.cpp
common/redisselect.h
common/selectable.h
pyext/swsscommon.i

Why/What I did:-
Change 1:
As per review comments on https://github.com/Azure/sonic-swss-common/pull/376
removed DB specific API from selectable class
to keep it generic.
Change 2: 
However to access to the Dervied Class Redis Select
DB API's via python we need to downcast the the Selectable Object
to RedisSelect object. 
To do this added Helper function  in swig .i file Ref: http://www.swig.org/Doc3.0/Python.html
How I verify:
After this change updated client caclmgrd to call new downcast API and verified we are getting correct information.
Sample Client Side code after this change -
(state, selectableObj) = sel.select(SELECT_TIMEOUT_MS)
if state != swsscommon.Select.OBJECT:
continue
redisSelectObj = swsscommon.CastSelectableToRedisSelectObj(selectableObj)
namespace = …

Removed DB specific get api's from Selectable class

---

common/subscriberstatetable.cpp
tests/redis_subscriber_state_ut.cpp

The issue statement:
If the use case of SubscriberStateTable meets below conditions:
1. First `Select::select()`, then `SubscriberStateTable::pop()` instead of `SubscriberStateTable::pops()`
2. The table under SubscriberStateTable is changing extreme high frequently
There is a rare timing risk inside the implementation of SubscriberStateTable, leading to a state that SubscriberStateTable holds two entries but `Select::select()` is stuck. If the table has new change (operation), SubscriberStateTable may recover.
The fix:
`SubscriberStateTable::hasCachedData` should return true if there are 2 or more entries internally, including entries in `m_buffer` which were read by previous `pops()`, or entries in `m_keyspace_event_buffer` which will be read by next `pops()`.
Ideally, we need to …

Fix SubscriberStateTable::hasCachedData formula for a timing risk

---

common/dbconnector.cpp
common/dbconnector.h

The original exception has too general info for debugging.
```
terminate called after throwing an instance of 'std::out_of_range'
what():  _Map_base::at
Aborted (core dumped)
```
After this fix:
```
terminate called after throwing an instance of 'std::out_of_range'
what():  Failed to find 15 database in  namespace
Aborted (core dumped)
```

Throw out_of_range exceptions with meaningful message for multi-DB and multi-namespace

---

common/redispipeline.h
common/redisreply.cpp
common/redisreply.h

Original we don't handle error code when talking with Redis by hiredis APIs. So we will realize it happening far away from the first place and get confusing error message.
Old
```
C++ exception with description "Memory exception, reply is null: Cannot allocate memory" thrown in the test body.
```
New
```
C++ exception with description "RedisResponseError: Failed to redisGetReply with CLIENT GETNAME: err=3: errstr=Server closed the connection" thrown in the test body.
```

Throw proper exceptions when talking with Redis

---

common/rediscommand.cpp

Fix memory leak if a `RedisCommand` object were to be reused. That is, a memory leak would have occurred if the methods `format()` or `formatArgv()` were to be used more than once on the same object. This change simply ensures that currently allocated memory gets freed before new memory gets allocated.

Fix memory leak in RedisCommand

---

common/warm_restart.cpp
common/warm_restart.h

1. Added new enums to WarmStartState
2. Added a new function to get the warm start state.
Refer to HLD: https://github.com/Azure/SONiC/pull/437

[warm reboot] Warm Reboot Support for EVPN VXLAN

---

pyext/swsscommon.i

What I did:
Added support in Swig file to cast Selectable object to SubscriberTable Object. 
Updated to use template function.
Why I did:
This way in application code we can  find out which subscribe
table select has return.
How I verify:
Verify after cast able to call getTableName() API and it return correct value.

Added support in Swig file to cast Selectable object to Subscriber Table object

---

common/netlink.cpp

Issue:
netlink out of memory seen for 8K neighbor updates.
Steps:
1. Config IP to 2 interfaces connected to ixia. Ethernet1 (21.0.0.1/16) and Ethernet4 (24.1.1.1/24)
2. DUT copp rules are as ARP CIR=2000 and IP2ME CIR=6000
3. Start Continuos Traffic (5G) is started from ixia connected to Ethernet4 with the DIP matching with the 8K ARP Host Range before learning ARP entries. These traffic will be software forwarded from linux kernel.
4. DUT is configured to learn ARP through ARP Reply packets
echo 1 > /proc/sys/net/ipv4/conf/Ethernet1/arp_accept
5. Start continuos ARP Reply Packet is sent from IXIA connected to Ethernet1 Port at 2K Packet/Secs with Host IP starting from 20.20.0.2 and Incrementing for 8K. 
After step (5), expectation is all 5G traffic must be forwarded from ASIC but not all …

netlink: Setting nl_socket buffer size to 3M from 2M

---

common/sonicv2connector.cpp
common/sonicv2connector.h
pyext/swsscommon.i
tests/test_redis_ut.py

1. pyext will pass empty string instead of None to SonicV2Connector ctor
2. add database name attributes
3. FieldValueMap class emulate the python dict interface

Fix SonicV2Connector interfaces

---

common/sonicv2connector.h
tests/test_redis_ut.py

To emulate the constructor of python version https://github.com/Azure/sonic-py-swsssdk/blob/master/src/swsssdk/dbconnector.py

SonicV2Connector supports host and decode_responses in constructor parameters

---

common/logger.cpp

Logs keeps coming every 1 second without any useful info, making it hard to use INFO level. Reducing to debug level
```
Oct 26 22:05:24.775111 str2-acs-02 INFO swss#orchagent: :- settingThread: void swss::Logger::settingThread() select timeout
Oct 26 22:05:25.776202 str2-acs-02 INFO swss#orchagent: :- settingThread: void swss::Logger::settingThread() select timeout
Oct 26 22:05:26.777356 str2-acs-02 INFO swss#orchagent: :- settingThread: void swss::Logger::settingThread() select timeout
```

Change log level for logger thread

---

common/Makefile.am
common/dbconnector.cpp
common/dbconnector.h
common/redis_multi.lua

When using SAI bulk in syncd, like create/remove route_entry, we want to have ability to update database as fast as possible, so best way would be to execute every mutable db command inside lua script to make things faster, rather than execute 1 by 1 operation which is done currently inside syncd

Add lua script for redis multi keys api hmset and del

---

common/dbconnector.cpp
common/dbconnector.h

Fixed a bug introduced by https://github.com/Azure/sonic-swss-common/pull/387
Fixed https://github.com/Azure/sonic-buildimage/issues/5697

Fix: treat DBConnector timeout=0 as infinite timeout

---

common/schema.h

sonic-swss-common: Changes to introduce a config table name to store card admin state
HLD: https://github.com/Azure/SONiC/pull/646
**- What I did**
Introduced a config table to store the card admin state in a modular chassis

Chassisd config table to store admin state

---

common/dbconnector.h
common/producerstatetable.h
common/producertable.h
common/table.h
pyext/swsscommon.i
tests/test_redis_ut.py

Otherwise SWIG will "smartly" translate it to `_del`
```
Warning 314: 'del' is a python keyword, renaming to '_del'
```
Since some application is using old function name, I keep some functions backward compatible.

[swig] translate C++ `del` to python `delete`

---

pyext/swsscommon.i

Without this change:
```
>>> from swsscommon import swsscommon
>>> swsscommon.DBConnector('CONFIG_DB', 0)
terminate called after throwing an instance of 'std::system_error'
what():  Unable to connect to redis (unix-socket): Cannot assign requested address
Aborted
```
With this change:
```
>>> from swsscommon import swsscommon
>>> swsscommon.DBConnector('CONFIG_DB', 0)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/dist-packages/swsscommon/swsscommon.py", line 1067, in __init__
this = _swsscommon.new_DBConnector(*args)
RuntimeError: Unable to connect to redis (unix-socket): Cannot assign requested address
>>>
```
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

[pyext] allow to catch exceptions raised in python

---

common/dbinterface.cpp
common/logger.h
pyext/swsscommon.i
tests/test_logger.py

Related to https://github.com/Azure/sonic-buildimage/issues/5992
It turns out that we need to set log level in snmpagent repo.

[swig] wrap logger.h

---

pyext/swsscommon.i
tests/test_redis_ut.py

Fixed https://github.com/Azure/sonic-buildimage/issues/5927 in common library.
Try to align to the behavior of redis-py python library in Python 2 environment. The parameter could be either a byte str or Unicode str.
```
>>> import redis
>>> r = redis.Redis(db=1)
>>> r.hgetall('ASIC_STATE:SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005be","mac":"FE:54:00:24:E6:9F","switch_id":"oid:0x21000000000000"}')
{'SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID': 'oid:0x3a0000000005bf', 'SAI_FDB_ENTRY_ATTR_TYPE': 'SAI_FDB_ENTRY_TYPE_DYNAMIC'}
>>> r.hgetall(u'ASIC_STATE:SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005be","mac":"FE:54:00:24:E6:9F","switch_id":"oid:0x21000000000000"}')
{'SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID': 'oid:0x3a0000000005bf', 'SAI_FDB_ENTRY_ATTR_TYPE': 'SAI_FDB_ENTRY_TYPE_DYNAMIC'} …
```

SWIG functions accept Unicode input

---

common/redisselect.cpp
common/select.cpp

Fixed https://github.com/Azure/sonic-buildimage/issues/5893
Original, `caclmgrd` crashed during ```fast-reboot``` with following log. Note that the exception handling already improves, so different from the log in the above issue
```
Dec  4 18:10:06.964034 sonic INFO caclmgrd[2660]: Traceback (most recent call last):
Dec  4 18:10:06.964250 sonic INFO caclmgrd[2660]:   File "/usr/local/bin/caclmgrd", line 670, in <module>
Dec  4 18:10:06.964377 sonic INFO caclmgrd[2660]:     main()
Dec  4 18:10:06.964509 sonic INFO caclmgrd[2660]:   File "/usr/local/bin/caclmgrd", line 666, in main
Dec  4 18:10:06.964631 sonic INFO caclmgrd[2660]:     caclmgr.run()
Dec  4 18:10:06.964751 sonic INFO caclmgrd[2660]:   File "/usr/local/bin/caclmgrd", line 610, in run
Dec  4 18:10:06.964891 sonic INFO …
```

Handle exception in Select

---

common/table.cpp

Because it is used only in pyext for backward compatible. New code should get separator from `database_config.json`
Fixed the first issue in https://github.com/Azure/sonic-buildimage/issues/5351

Remove extension of tableNameSeparatorMap

---

common/dbconnector.cpp
common/dbconnector.h
common/dbinterface.cpp
common/dbinterface.h
common/sonicv2connector.cpp
common/sonicv2connector.h

Add support for hexists call.
Tested using below code snippet:
```
from swsscommon.swsscommon import SonicV2Connector
db = SonicV2Connector(host='127.0.0.1')
db.connect(db.COUNTERS_DB)
db.connect(db.ASIC_DB)
ex = int(db.hexists(db.COUNTERS_DB, "COUNTERS_PORT_NAME_MAP", "Ethernet0"))
if ex == 1:
print "Exists"
else:
print "Do not exists"
```

Add support for hexists call

---

common/rediscommand.h

Signed-off-by: Ze Gan <ganze718@gmail.com>

[rediscommand] Add missed vector header to rediscommand.h

---

common/dbconnector.h
common/dbinterface.cpp
common/pubsub.h
common/redistran.cpp

Include several fixes and refactors:
- Simply refactor DBConnector hgetall()
- Fix RedisTransactioner: handle empty deque
- Move complex class constructor as explicit, and fix several mistaken copy constructor usage

Fix bug: RedisTransactioner pops empty container, mistaken copy constructor usage

---

common/Makefile.am
common/configdb.cpp
common/configdb.h
common/dbconnector.cpp
common/dbconnector.h
common/dbinterface.cpp
common/dbinterface.h
common/pubsub.cpp
common/pubsub.h
common/redisreply.cpp
common/redisreply.h
common/redisselect.cpp
common/redisselect.h
common/redistran.cpp
common/sonicv2connector.cpp
common/sonicv2connector.h
configure.ac
pyext/py2/Makefile.am
pyext/py3/Makefile.am
pyext/swsscommon.i

They are originally implemented by python in https://github.com/Azure/sonic-py-swsssdk/
We plan to deprecated the python version which based on redis-py.
The new implementation is based on hiredis C++ library.
Tested manually with sonic-config-engine unit tests.

Implement ConfigDBConnector and ConfigDBPipeConnector in C++

---

common/subscriberstatetable.cpp

Fixed https://github.com/Azure/sonic-buildimage/issues/6313
There is latency between event happens and notification data is consumed. Change log level from error to notice, since this is a valid use case.

Lower the log level for outdated key for SubscriberStateTable notification

---

common/dbconnector.cpp
common/dbconnector.h

STL containers are only thread safe for reads. But not for writes. protect the db information variables with rwlock.
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[dbconnector] protect db information with mutex

---

debian/control

This PR defines libboost v1.71.0 as an alternative package
for libswsscommon.
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

[packaging]: Add Support For Libboost v1.71.0

---

common/dbconnector.cpp
tests/redis_ut.cpp

When calling dump() it will generate {} instead null
Signed-off-by: kcudnik <kcudnik@gmail.com>

[dbconnector] Make sure json is declared as non null object

---

common/configdb.cpp
common/configdb.h
common/dbconnector.cpp
common/dbconnector.h
common/sonicv2connector.cpp
common/sonicv2connector.h
pyext/swsscommon.i
tests/redis_ut.cpp
tests/test_redis_ut.py

Add missing functions for ConfigDBConnector, including
- ConfigDBConnector.get_redis_client(...)
- ConfigDBConnector.CONFIG_DB
- ConfigDBConnector.get_redis_client(...).flushdb()
- ConfigDBConnector.INIT_INDICATOR
- ConfigDBConnector.db_connect(...): support optional parameters
Tested in unit test:
1. this repo: add unit testcases for all the new functions.
2. sonic-config-engine
3. sonic-utilities
Tested in DUT:
1. `sudo config load_minigraph -y`
2. snmpwalk snmpagent on 1.3.6.1.4.1.9.9.187

[swig] Add missing functions for ConfigDBConnector

---

common/dbconnector.cpp
tests/redis_multi_ns_ut.cpp

Update to make getNamespaces() API at par with the get_ns_list() in swsssdk. So this API 
1. Will give back all namespaces including the global namespace ('')
2. Will not preload the Global database_config.json. The application should call SonicDBConfig::initializeGlobalConfig explicity.

Update to make getNamespaces() API at par with get_ns_list() in swsssdk

---

common/schema.h

Adding LINKMGR cfg table name to config db macros and
MUX_LINKMGR state table to state db macros.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

[swss-common] Add LINKMGR CFG and MUX LINKMGR state table names

---

common/sonicv2connector.h
tests/test_redis_ut.py

The function `get_all` in `SonicV2Connector` returns a FieldValueMap which is not json serializable. This object type will cause failures in fast reboot dump. Converting the object to a dictionary to avoid fast reboot failures.

Convert return value of get_all function in SonicV2Connector to dict

---

debian/control

libswsscommon-dev is not usable without libboost-dev package, meaning I cannot compile with headers which include boost libraries. Make it implicitly install by apt-get install -f
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>

[debian/control] libswsscommon-dev depends on libboost-dev

---

common/dbconnector.cpp

Issue: When /var/run/redis/sonic-db/database_config.json file is missing,
RedisContext destructor calls redisFree on invalid pointer.
Fix:     Initialize redisContext to NULL in order to avoid deallocating an
invalid memory address when RedisContext destructor is being called.

[dbconnector] Initialize redisContext

---

common/sonicv2connector.h
tests/test_redis_ut.py

This is to fix a bug after replacing swsssdk with swsscommon.
```
$ show reboot-cause history                                          
Traceback (most recent call last):
File "/usr/local/bin/show", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, …
```

[swig] translate SonicV2Connector::keys return type from C++ vector<string> to Python list

---

pyext/swsscommon.i
tests/test_redis_ut.py

By default, SWIG does not enable support for multithreaded Python applications. More specifically, the Python wrappers generated by SWIG will not release the Python's interpreter's Global Interpreter Lock (GIL) when wrapped C/C++ code is entered. Hence, while any of the wrapped C/C++ code is executing, the Python interpreter will not be able to run any other threads, even if the wrapped C/C++ code is waiting in a blocking call for something like network or disk IO.
ref: http://www.swig.org/Doc4.0/Python.html#Python_multithreaded
But the solution is for swig 4.0. The PR fix it in swig 3.0.

[swig] allow threads

---

common/schema.h

Signed-off-by: Venkatesan Mahalingam <venkatesan_mahalinga@dell.com>
Please refer [HLD](https://github.com/Azure/SONiC/pull/638) and [swss](https://github.com/Azure/sonic-swss/pull/1707) PRs for more information.
What I did
Support for in-band-mgmt via management VRF
Why I did it
Other than eth0, mgmt VRF should have in-band L3 interfaces as well.
How I verified it
In-progress

Support for in-band-mgmt via management VRF.

---

common/table.h
pyext/swsscommon.i
tests/test_redis_ut.py

Due to the SWIG limitation on tuples, it's not straightforward to wrap the C++ `TableEntryPoppable::pops()`. Here I implement a workaround `TableEntryPoppable.pops()` which returns a tuple of 3 arrays, and another helper function to transpose the result to emulate the behavior of C++ `TableEntryPoppable::pops()`.
Tested in unit test.

[swig] Implement TableEntryPoppable.pops()

---

common/schema.h

MUX Metrics table will be used to collect metrics relevant to the
MUX hardware.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

[swss-common] Add MUX Metrics Table

---

common/configdb.cpp
common/configdb.h
tests/test_redis_ut.py

Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>
The PR https://github.com/Azure/sonic-buildimage/pull/6920 adds the support for swsscommon in `hostcfgd`. The PR test failure are seen because the `config_db.subscribe` doesnt work with swsscommon. This PR adds the support for the following python APIs
- `config_db.subscribe`
- `config_db.unsubscribe`

Add support for config_db subscribe and unsubscribe python apis

---

common/configdb.cpp
tests/test_redis_ut.py

swss-common: Fix config save error for non-hash key
- Fixing https://github.com/Azure/sonic-swss-common/issues/467
- Cleanup https://github.com/Azure/sonic-swss-common/pull/465
Signed-off-by: Runming Wu runmingwu@gmail.com

Fix config save error for non-hash key.

---

.azure-pipelines/build_and_install_module.sh

When run "make modules_prepare", it prompts an ask as below:
Microsoft Network Devices (NET_VENDOR_MICROSOFT) [Y/n/?] (NEW)
It should be caused by the new version of the kernel config mis-match with existing one.

Fix config prompt question issue

---

common/logger.cpp
common/logger.h

add extra parameter  to  linkToDbNative , which is default to "NOTICE" to allow  daemons to set their own log level easily.
Example:
Logger::linkToDbNative("portsyncd"); // by default "NOTICE"
Logger::linkToDbNative("portsyncd", "INFO"); //explicit "INFO"

modify the logger for more flexable change of log level

---

common/dbinterface.cpp
common/dbinterface.h
tests/test_redis_ut.py

Fixes https://github.com/Azure/sonic-buildimage/issues/8202
- Fix pubsub channel timeout unit
- Reset context err before next redisGetReply, otherwise later redisGetReply early return on no data, and burn CPU core in a loop.
ref: https://github.com/redis/hiredis/issues/332

Fix DBInterface blocking operations

---

common/consumerstatetable.cpp

This variable comes from getTableNameSeparator() method.

Modify the hardcode separator ":" to variable.

---

common/linkcache.cpp

**Why I did it**
The getLinkByName may fail because of the outdated netlink cache
**How I did it**
Refill the netlink cache when we fail to get link object.
**How to verify it**
**Description for the changelog**
**A picture of a cute animal (not mandatory but encouraged)**

[netlink] refill netlink cache when failing to get the link object by name

---

common/concurentmap.h
common/concurrentmap.h
common/logger.cpp
common/logger.h

Signed-off-by: kcudnik <kcudnik@gmail.com>
Fixes https://github.com/Azure/sonic-buildimage/issues/8177
I also made some minor code style refactoring

[logger] Make map access thread safe and proper terminate thread

---

.azure-pipelines/build-docker-sonic-vs-template.yml

We should use 202012 branch to download `sonic-buildimage.vs`

Fix azure pipeline DownloadPipelineArtifact source branch

---

common/rediscommand.cpp
common/rediscommand.h
common/table.cpp
common/table.h
tests/redis_ut.cpp

[table.h/rediscommand.h] 
* Updated table.h with a new set() routine capable of also setting TTL on an entry.
* Updated rediscommand.h with the EXPIRE command
Signed-off-by: Cosmin Jinga <v-cjinga@microsoft.com>

Added support for setting TTL on a Table managed entry.

---

common/database_config.json

Since ASIC_DB, as well its COUNTER_DB, FLEX_COUNTER_DB always use separator ':', GB_ASIC_DB should use same. We use same sairedis interface/logic to update ASIC_DB and GB_ASIC_DB.

[gearbox] Update GB_ASIC_DB separator to ':'

---

.azure-pipelines/build-template.yml

The files swsscommon_wrap.cpp is generated by swig, which are long files and the coverage is relative low. Remove them from the coverage report.

[ci] Remove SWIG generated files from coverage report

---

debian/python-swsscommon.install
debian/python3-swsscommon.install

The file `_swsscommon.a` in the python deb packages takes > 33 MB, and it is not used.
Remove it to save disk space.

Exclude *.a files from python deb packages

---

common/schema.h

Add vnet route tunnel and advertise network tables for state_db in swss-common schema

[schema] Add vnet route tunnel and advertise network tables for state_db

---

azure-pipelines.yml
common/Makefile.am
common/saiaclschema.cpp
common/saiaclschema.h
tests/Makefile.am
tests/saiaclschema_ut.cpp

Submission containing materials of a third party:
Copyright Google LLC; Licensed under Apache 2.0
Co-authored-by: Akarsh Gupta <akarshgupta@google.com>
Co-authored-by: Ashish Singh <ashishksingh@google.com>
Co-authored-by: Jay Hu <jiarenhu@google.com>
Co-authored-by: Manali Kumar <manalikumar@google.com>
Co-authored-by: Richard Yu <richardyu@google.com>
Co-authored-by: Robert J. Halstead <rhalstea@google.com>
Co-authored-by: Runming Wu <runmingwu@google.com>
Co-authored-by: Srikishen Pondicherry Shanmugam <kishanps@google.com>
Co-authored-by: Vivek Ramamoorthy <vivekmoorthy@google.com>
Co-authored-by: Yilan Ji <yilanji@google.com>
Signed-off-by: Don Newton don@opennetworking.org

[PINS] Add AppDB ACL schema values shared between the P4RT app and P4Orch

---

.azure-pipelines/build-template.yml
debian/control
debian/python-swsscommon.dirs
debian/python-swsscommon.install
debian/rules

Instead of using the distro version to determine if the Python 2
bindings should be built, use deb profiles instead to specify if they
should be built or not. The main reason of this is that normal .install
and .dirs files can be used for both the Python 2 and Python 3 bindings,
instead of .install/.dir files for Python 3 and debian/rules for Python
2.
More details on build profiles are [here](https://wiki.debian.org/BuildProfileSpec).
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

Use build profiles instead of distro version for Python 2 binding build

---

common/schema.h

Taking the changes in https://github.com/Azure/sonic-swss-common/pull/560 to 202012 branch
Add vnet route tunnel and advertise network tables for state_db in swss-common schema

[202012][schema] Add vnet route tunnel and advertise network tables for state_db

---

.azure-pipelines/build-docker-sonic-vs-template.yml

Change reference from CI build to official build. This PR will unblock the PR checker of swss-common in 202012 branch.

Change sonic-buildimage.vs artifact source from CI build to official build

---

common/consumerstatetable.cpp
common/consumertable.cpp
common/producerstatetable.cpp
common/producertable.cpp
common/table.h

Reverts Azure/sonic-swss-common#574
The real cause is fixed at https://github.com/Azure/sonic-sairedis/pull/995. Continue to commit bd4d0ce again.

Revert "Revert "[TableBase] Make channel name from both table name and databa…"

---

README.md
azure-pipelines.yml

Updating the README to reflect the new dependency. Also, removing duplicate libgtest-dev from the azure-pipeline script.

Update README for gmock

---

common/configdb.h
tests/test_redis_ut.py

Currently if someone wishes to use ConfigDBConnector to operate on updates coming from CONFIG_DB AND they wish to pull all the initial data from the table to initialize their only option is to pull the data and then run the `listen()` method on ConfigDBConnector.
This creates a "blackout" period where between the time the tables are downloaded and the `listen()` method is called, any new updates to CONFIG_DB will not be handled.
To resolve this I have changed two things in ConfigDBConnector. All of which are 100% backwards compatible...
1. I split `listen()` into `listen()` and `process()` where `listen()` may now be called with `start=False` as an argument which does not start immediately processing updates from CONFIG_DB and calling handlers. This allows you to call `listen()` *first* …

Add API endpoints to ConfigDBConnector to support pre-loading data without blackout

---

common/schema.h

The name MACSEC_SA_PLUGIN_FIELD is defined for macsec sa plugins, used by https://github.com/Azure/sonic-swss/pull/2218.

[macsec] Add MACSEC_SA_PLUGIN_FIELD

---

common/ipprefix.cpp
common/ipprefix.h
tests/ipprefix_ut.cpp

Why I did this?
Need to construct a IpPrefix instance from ip structure and mask length.

Add a ctor for IpPrefix to accept ip structure and mask

---

common/schema.h

This PR is to define a new table name `TC_TO_DSCP_MAP` for DSCP rewriting for tunnel traffic.
HLD https://github.com/Azure/SONiC/pull/950

Define `TC_TO_DSCP_MAP` for DSCP rewriting for tunnel traffic 

---

common/producerstatetable.cpp
common/producerstatetable.h
tests/redis_piped_state_ut.cpp
tests/redis_state_ut.cpp
tests/test_redis_ut.py

swss-common: Added batched APIs in ProducerStateTable.
HLD: https://github.com/Azure/SONiC/pull/959
Signed-off-by: Runming Wu [runmingwu@gmail.com](mailto:runmingwu@gmail.com)

Added batched APIs in ProducerStateTable.

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build-sairedis-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/template-get-source-branch.yml
.azure-pipelines/test-docker-sonic-vs-template.yml
azure-pipelines.yml

1. Parameterize pipeline. When checkout new release branch, we don't need manually setup azp.
2. Use common lib pipeline instead of buildimage pipeline to get higher success rate.
3. Clean workspace when downloading external packages. This will ensure package version matching.

[ci] Parameterize pipeline and improve azure pipeline

---

common/notificationconsumer.cpp
tests/redis_piped_ut.cpp
tests/redis_ut.cpp

Also make op, data, fvs vector local to while loop where they are actually used in pops().
Co-authored-by: Ashish Singh [ashishksingh@google.com](mailto:ashishksingh@google.com)

Clear the fvs vector before popping the message out of notification consumer queue.

---

common/selectabletimer.cpp
common/selectabletimer.h
tests/Makefile.am
tests/redis_ut.cpp
tests/timer_ut.cpp

Add mutex protection to avoid having the timer expiration reset due to
subsequent calls of start()
Avoid having the timer expiration reset due to subsequent calls of start()
Add mutex protection to start() and stop()
Signed-off-by: Dante Su <dante.su@broadcom.com>

selectabletimer: add mutex to start() and stop()

---

common/portcounter.lua
tests/test_countertable.py

In local function `get_gbcounter` of portcounter.lua, need to check the return value of redis HGET. We can do addition operation only if counter ID exists and returns its value number.

[portcounter] Check if counter ID exists before arithmetic operation 

---

common/redisreply.cpp
common/redisreply.h
common/stringutility.h
sonic-db-cli/sonic-db-cli.cpp
sonic-db-cli/sonic-db-cli.h
tests/cli_ut.cpp

This PR is to cherry-pick #631 to `202111` branch.
[sonic-cli] Fix sonic-db-cli output format not backward compatible with python version issue. #631
Signed-off-by: qiluo-msft <qiluo@microsoft.com>, kcudnik <kcudnik@microsoft.com>

Cherry-pick '[sonic-cli] Fix sonic-db-cli output format not backward compatible with python version issue.' from master branch.

---

common/sonicv2connector.cpp
common/sonicv2connector.h
tests/test_redis_ut.py

Following config command in sonic-utility using an API does not exist in swss-common:
sudo config rate smoothing-interval 100
https://github.com/Azure/sonic-utilities/blob/e089b964ef0d38d8c691eb3e551e479c0c68dd96/config/main.py#L6548
counters_db.set('COUNTERS_DB', 'RATES:PORT', 'PORT_SMOOTH_INTERVAL', interval) <== interval is an int value.
Currently swss-common only support string value:
int64_t SonicV2Connector_Native::set(const std::string& db_name, const std::string& _hash, const std::string& key, const std::string& val, bool blocking)
Add SonicV2Connector::set method for int value.
Pass all test case.
Add UT to cover new API.
Add SonicV2Connector::set method for int value.

Add SonicV2Connector::set method for int value.

---

common/redisreply.cpp
tests/cli_ut.cpp

Fix sonic-db-cli issue on chassis:
[chassis]After sonic-db-cli C++ implementation, database.sh fails to start database-chassis on Supervisor card
https://github.com/Azure/sonic-buildimage/issues/11473
The reason of this issue is because c++ version sonic-db-cli output different with python version:
Here is Python version result:
admin@vlab-01:~$ /usr/local/bin/sonic-db-cli -s PING
PONG
admin@vlab-01:~$ /usr/local/bin/sonic-db-cli STATE_DB PING
True
Here is c++ version result:
admin@vlab-01:~$ /usr/local/sonic-db-cli -s PING
PONG
admin@vlab-01:~$ /usr/local/sonic-db-cli STATE_DB PING
PONG
Change RedisReply::formatReply() to return bool string for PING command.
Pass all test case.
Add new UT cover change.
Fix sonic-db-cli issue on chassis:
[chassis]After sonic-db-cli C++ implementation, …

Fix PING database command not return bool string issue.

---

pyext/swsscommon.i

Fix epoll and socket resurce leak issue:
[chassis] Too many open files error and unable to connect to redis socket error
https://github.com/Azure/sonic-buildimage/issues/10870
The reason of this issue is in SWIG any method return a new object need decorate with %newobject, so SWIG will generate code to release C++ object when python wrapper object released:
https://www.swig.org/Doc4.0/SWIGDocumentation.html#Customization_ownership
Update swsscommon.i to decorate return new object methods with %newobject
Pass all test case.
Run following code in python and validate there is no epoll and socket leak:
from swsscommon.swsscommon import SonicDBConfig
from swsscommon.swsscommon import SonicV2Connector
import gc
SonicDBConfig.load_sonic_global_db_config()
SonicDBConfig.get_ns_list()
db = …

Fix epoll and socket resource leak issue.

---

common/redisreply.cpp
common/redisreply.h
tests/cli_ut.cpp

Fix sonic-db-cli dictionary output format not backward compatible issue: https://github.com/sonic-net/sonic-buildimage/issues/11945
Improve redis reply format method, keep same format with redis-py.
Add c++ unit test to cover all code.
Pass all E2E test scenario.
Fix sonic-db-cli dictionary output format not backward compatible issue.

Fix sonic-db-cli dictionary output format not backward compatible issue.

---

.azure-pipelines/build-sairedis-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/test-docker-sonic-vs-template.yml
BUILD
azure-pipelines.yml

Support sonic-swss-common build and link with libyang for read Yang model defaut value.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.

Modify azure pipeline to install libyang in azure pipeline steps.

---

common/redisreply.cpp
common/redisreply.h
tests/cli_ut.cpp

**This is to backport PR fix https://github.com/sonic-net/sonic-swss-common/pull/678 to 202205 branch.
since the original PR has not been cherry-picked yet, so create this PR directly to backport the fix.
If the original PR will be cherry-picked, then this PR should be closed.**
Fix sonic-db-cli dictionary output format not backward compatible issue: https://github.com/sonic-net/sonic-buildimage/issues/11945
Improve redis reply format method, keep same format with redis-py.
Add c++ unit test to cover all code.
Pass all E2E test scenario.
Fix sonic-db-cli dictionary output format not backward compatible issue.

[202205] Fix sonic-db-cli dictionary output format not backward compatible issue

---

common/configdb.cpp
common/dbconnector.cpp
common/dbconnector.h

Add DBConnector::getall() for profile provider feature.
Add  DBConnector::getall() method.
Move content of ConfigDBConnector_Native::get_config() to DBConnector::getall()
Pass all existing UT and E2E test.
Add DBConnector::getall() method and refactor ConfigDBConnector_Native::get_config().

Add DBConnector::getall() method and refactor ConfigDBConnector_Native::get_config().

---

common/Makefile.am
common/redis_table_waiter.cpp
common/redis_table_waiter.h
common/restart_waiter.cpp
common/restart_waiter.h
pyext/swsscommon.i
tests/Makefile.am
tests/redis_table_waiter_ut.cpp
tests/restart_waiter_ut.cpp

**Depends on:**
- https://github.com/sonic-net/sonic-sairedis/pull/1100
- https://github.com/sonic-net/sonic-utilities/pull/2286
- https://github.com/sonic-net/sonic-buildimage/pull/11594
**Why I did this?**
Daemons which are not related to warm/fast restart might affect the performance of warm/fast restart. A hardcoded start up delay is the current solution to avoid this.
This PR implements a function to wait warm/fast restart done. This function provided a efficiency and graceful way for daemons to wait warm/fast restart done.
**How I did it?**
Implement a utility function RestartWaiter::waitRestartDone. This function waits warm restart done flag in STATE DB and return true if the flag is set by warm restart finalizer. This function is also exposed as python extension so that python …

[Fast/Warm restart] Implement helper class for waiting restart done

---

common/logger.cpp

What I did
Check whether a pointer created by dynamic_cast is null before using it.
Why I did it
dynamic_cast<ConsumerStateTable *>(selectable) may return NULL

Check whether a pointer created by dynamic_cast is null before using it.

---

sonic-db-cli/sonic-db-cli.cpp
tests/cli_ut.cpp

Fix sonic-db-cli  PING/SAVE/FLUSHALL command crash when database config file not ready issue:
https://github.com/sonic-net/sonic-buildimage/issues/12047
When run PING/SAVE/FLUSHALL command, catch database initialize failed exception and return 1.
Pass all existing UT and E2E test.
Add new UT to cover changed code.
Manually test, sonic-db-cli will return 1 when run PING command and can't find config file:
azureuser@a7f66d2b794c:/sonic/src/sonic-swss-common$ ./sonic-db-cli/sonic-db-cli PING
An exception of type Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json occurred. Arguments:
/sonic/src/sonic-swss-common/sonic-db-cli/.libs/sonic-db-cli PING
azureuser@a7f66d2b794c:/sonic/src/sonic-swss-common$ echo $?
1
Fix sonic-db-cli  PING/SAVE/FLUSHALL command …

[sonic-db-cli] Fix sonic-db-cli crash when database config file not ready issue.

---

common/redispipeline.h
common/redisreply.cpp
common/redisreply.h

This is a manually cherry pick of https://github.com/sonic-net/sonic-swss-common/pull/384 , because there is merge conflict happen.
* Add new exception RedisResponseError
* Rename to RedisError
* Throw bad_alloc when ouf of memory
* Handle and throw exception in RedisPipeline

[cherry-pick] [201911] Throw proper exceptions when talking with Redis

---

.azure-pipelines/build_and_install_module.sh
azure-pipelines.yml

Motivation: 
Currently we specify swss-common to use libboost-serialization1.71 to be used which is fine when building swss-common inside of slave-buster container. However, when building swss-common inside bullseye, libboost-serialization1.71 is not supported. We have installed libboost-serialization1.74 inside bullseye and are making change in swss-common to use highest version of libboost-serialization available (1.71 for buster or 1.74 for bullseye)

Update libboost-serialization1.71 to libboost-serialization-dev to use highest version available

---

common/configdb.cpp
common/dbconnector.h
tests/test_redis_ut.py

Fix memory leak issue in ConfigDBConnector:
[chassis] Too many open files error and unable to connect to redis socket error https://github.com/Azure/sonic-buildimage/issues/10870
The reason of this issue is DBConnector::pubsub() will return a pointer, and following code call this method but never release the returned pointer:
```
void ConfigDBConnector_Native::db_connect(string db_name, bool wait_for_init, bool retry_on)
{
m_db_name = db_name;
m_key_separator = m_table_name_separator = get_db_separator(db_name);
SonicV2Connector_Native::connect(m_db_name, retry_on);
if (wait_for_init)
{
auto& client = get_redis_client(m_db_name);
auto pubsub = client.pubsub(); <== this pointer not delete later.
```
Also change DBConnector::pubsub() to deprecated for none SWIG scenario.
Change …

[cherry-pick] [202205] Fix memory leak issue in ConfigDBConnector.

---

.azure-pipelines/build-template.yml

Why I did it
sonic-gnmi need use libswss-common bullseye artifact from this pipeline.
How I did it
Modify azure pipeline to install libyang from common-libs artifact.
How to verify it
Pass all UT.
Which release branch to backport (provide reason below if selected)
201811
201911
202006
202012
202106
202111
Description for the changelog
sonic-gnmi need use libswss-common bullseye artifact from this pipeline.
Link to config_db schema for YANG module changes
A picture of a cute animal (not mandatory but encouraged)

[CI]Install libyang from common-lib when build bullseye

---

debian/libswsscommon-dev.install

sonic-gnmi needs to reuse swsscommon.i
Install swsscommon.i with libswsscommon-dev
Install libswsscommon-dev and check /usr/share/swss
Install swsscommon.i with libswsscommon-dev.

Install swsscommon.i with libswsscommon-dev

---

.azure-pipelines/build-template.yml
common/Makefile.am
common/configdb.h
common/countertable.h
common/dbconnector.h
common/decoratorsubscriberstatetable.cpp
common/decoratorsubscriberstatetable.h
common/decoratortable.cpp
common/decoratortable.h
common/defaultvalueprovider.h
common/producerstatetable.h
common/producertable.h
common/sonicv2connector.h
common/table.h
debian/libswsscommon-dev.install
goext/Makefile
goext/swsscommon.i
goext/swsscommon_test.go
pyext/swsscommon.i
tests/test_decorator_ut.py

Cherry-pick from master branch 
* f312634 -  Install swsscommon.i with libswsscommon-dev (#717) (6 minutes ago) [ganglv]
* 61b7888 - Use SWIGPYTHON to improve SWIG for GO wrapper. (#714) (6 minutes ago) [ganglv]
* 1c10dac - Add decorator for Yang default value.  (#713) (6 minutes ago) [Hua Liu]

[202211] cherry-pick from master

---

common/schema.h

Refer to https://github.com/sonic-net/sonic-swss/pull/2559
This PR has been raised to enable support for tc-dot1p qos map configuration. The above mentioned PR is dependent on this commit.
- [ x] 202205

Support for TC-DOT1p qos map

---

.azure-pipelines/build-template.yml

The custom branch we were using previously has since been deleted. That branch appears to have some fix for searching for the source file (for a gcda file) recursively. I don't know if it's needed or not today, but using the stock gcovr 5.2 (from the official repo) appears to work.
Copied from sonic-net/sonic-sairedis#1174.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

Switch to using stock gcovr 5.2

---

.azure-pipelines/build-sairedis-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
azure-pipelines.yml

Use correct sonic-slave docker image as environment.
Fix build issue.

Fix sonic-slave docker image environment issue.

---

.azure-pipelines/build-template.yml

* Switch to using stock gcovr 5.2
The custom branch we were using previously has since been deleted. That branch appears to have some fix for searching for the source file (for a gcda file) recursively. I don't know if it's needed or not today, but using the stock gcovr 5.2 (from the official repo) appears to work.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

Switch to using stock gcovr 5.2 (#726)

---

common/events.cpp
common/events_pi.h

Motivation for PR:
Refactored code to retire runtime id from destructor to drop_publisher

Refactor eventpublisher deinit

---

common/producerstatetable.h

Make ProducerStateTable class inheritable. 
Change the dtor of ProducerStateTable to virtual method.
Change the dtor of ProducerStateTable to virtual method.

Change the dtor of ProducerStateTable to virtual method

---

common/redispipeline.h

Because RedisPipeline is not thread safe, in c++ if code call exit() from another thread, the dtor of RedisPipeline will  be called from another thread and trigger a race condition issue.
RedisPipeline ignore flush when call dtor from another thread.
RedisPipeline ignore flush when call dtor from another thread.

RedisPipeline ignore flush when call dtor from another thread.

---

common/netlink.cpp

As error is seen in fdbsyncd with netlink reports "out of memory on reading a netlink socket" It is seen when kernel is sending 10k remote mac to fdbsyncd.
- What I did
Increase the buffer size of the netlink buffer from 3MB to 16MB
- How I did it
Increase the buffer size in the API nl_socket_set_buffer_size
- How to verify it
Verified with 10k remote mac, and restarting the fdbsyncd process. So that kernel send the bridge fdb dump to the fdbsyncd.
Verified that the netlink buffer error is not reported in the sys log.
Signed-off-by: kishore.kunal@broadcom.com

Increase the netlink buffer size from 3MB to 16MB.

---

pyext/swsscommon.i

Cherry-picking this #651 for 202205 branch.
Fix epoll and socket resurce leak issue:
[chassis] Too many open files error and unable to connect to redis socket error https://github.com/Azure/sonic-buildimage/issues/10870
The reason of this issue is in SWIG any method return a new object need decorate with %newobject, so SWIG will generate code to release C++ object when python wrapper object released: https://www.swig.org/Doc4.0/SWIGDocumentation.html#Customization_ownership
Update swsscommon.i to decorate return new object methods with %newobject
Pass all test case.
Run following code in python and validate there is no epoll and socket leak:
from swsscommon.swsscommon import SonicDBConfig
from swsscommon.swsscommon import SonicV2Connector import gc …

[202205] Fix epoll and socket resource leak issue. (#651)

---

.azure-pipelines/build-sairedis-template.yml

The path to the sairedis test binary (for `setcap`) has changed after sonic-net/sonic-sairedis#1197. Update the path here.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

[CI] Update path to sairedis tests

---

sonic-db-cli/main.cpp
sonic-db-cli/sonic-db-cli.cpp
sonic-db-cli/sonic-db-cli.h
tests/cli_ut.cpp

sonic-db-cli is porting from python version. in python version, when any exception happen sonic-db-cli will crash but will not generate core dump file. but in c++ version crash will generate a core dump.
Fix sonic-db-cli to avoid a core dump file generated.
Catch all exception in sonic-db-cli to avoid core dump generated.
Fix sonic-db-cli to avoid a core dump file generated.

Prevent sonic-db-cli generate core dump

---

common/profileprovider.h

sonic-gnmi will break if any header file contains 'common' in path
Fix common path issue in profileprovider.cpp
Fix common path issue in profileprovider.cpp

Fix common path issue in profileprovider.cpp

---

goext/Makefile

sonic-gnmi will break if any header file contains 'common' in path
Improve unit test to detect common path issue
Improve unit test to detect common path issue

Improve unit test for go wrapper

---

.azure-pipelines/build-sairedis-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/build_and_install_module.sh
.azure-pipelines/test-docker-sonic-vs-template.yml
azure-pipelines.yml

cherry-pick PRs:
```
43e6827 Update path to sairedis tests (#747)
8491082 [ci] Continue on error when running test.
5000aa1 [ci] Fix apt-get install unable locate package issue. (#753)
e50ee9e Simplify azure pipeline build template (#729)
7d30c9f Fix sonic-slave docker image environment issue. (#727)
```

Cherry-pick PRs in master branch to unblock PR checks.

---

common/configdb.h
tests/test_redis_ut.py

Fix mod_config with empty config will delete table bug.
Fix mod_config with empty config will delete table bug:
When config is None, delete table.
When config is empty, no action.
Add new UT to cover mod_config wity None and empty config case.
Fix mod_config with empty config will delete table bug.

Fix mod_config with empty config will delete table bug.

---

common/logger.cpp
common/logger.h
tests/logger_ut.cpp

This is to support adding custom observers to the swss logger.
With `restartLogger`, now applications could start logger with the following lines:
```
linkToDb(demoDb, myCustomPrioNotify, defaultPrio);
restartLogger()
```
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

[logger] Add public `restartLogger` to restart logger thread

---

common/schema.h

This PR is to backport change in PR #748 into `202211` branch.
HLD https://github.com/sonic-net/SONiC/pull/1261

[202211][cherry-pick]Define ACL_TABLE and ACL_RULE table in STATE_DB

---

.azure-pipelines/build-sairedis-template.yml

sonic-swss-common/.azure-pipelines/build-sairedis-template.yml requires similar changes as what sonic-sairedis PR# 1230 has introduced in sonic-sairedis/.azure-pipelines/build-template.yml

Create directory /var/run/sswsyncd and add capability for syncd unittest

---

common/zmqclient.cpp
common/zmqserver.cpp
common/zmqserver.h

Improve ZMQ performance to use all bandwidth.
Increase ZMQ send/recv buffer and send with no block mode
Manually verified the change make ZMQ use all bandwidth.
Improve ZMQ performance to use all bandwidth.

Improve ZMQ to use all bandwidth

---

tests/zmq_state_ut.cpp

Fix ZMQ UT timeout issue
ZMQ UT timeout, because UT code bug: before consumer thread receive all data, producer been released so some data never been send. so consumer wait for data untill timeout.
Improve code, exit producer after consumer receive all data.
Fix ZMQ UT timeout issue.

Fix ZMQ UT timeout issue.

---

.gitignore

After build there are a few generated files from automake and libtool not excluded in the .gitignore.
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
common/.dirstamp
pyext/py2/.dirstamp
pyext/py3/.dirstamp
sonic-db-cli/.dirstamp
sonic-db-cli/sonic-db-cli
tests/.dirstamp
```
Adding these files into .gitignore in order to avoid accidentally adding them into PR later.

Add .dirstamp and generated sonic-db-cli into .gitignore.

---

m4/python3.m4

I am using python 3.10 on my dev machine and hitting the build error below, due to incorrect version being detected and it is trying to look for Python.h in /usr/include/python3.1 instead of /usr/include/python3.10.
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -Icommon -I/usr/include/python3.1 -O0 -g -MT pyext/py3/pyext_py3__swsscommon_la-swsscommon_wrap.lo -MD -MP -MF pyext/py3/.deps/pyext_py3__swsscommon_la-swsscommon_wrap.Tpo -c pyext/py3/swsscommon_wrap.cpp  -fPIC -DPIC -o pyext/py3/.libs/pyext_py3__swsscommon_la-swsscommon_wrap.o
pyext/py3/swsscommon_wrap.cpp:173:11: fatal error: Python.h: No such file or directory
173 | # include <Python.h>
|           ^~~~~~~~~~
```
The reason is because we are using `sys.stdout.write(sys.version[[:3]])` to detect the version, which …

Fix python3 version detection in makefile.

---

pyext/swsscommon.i

Improve go language SWIG wrapper: add exception mapping and enable directors feature.
Microsoft ADO (number only): 24117097
Go language not support c++ exception.
Class inheritance information missing in go wrapper.
Add exception handler to mapping c++ exception to go panic.
Enable directors feature to convert c++ class inheritance information to go wrapper class inheritance information.
Improve go language SWIG wrapper: add exception mapping and enable directors feature.

 Improve go language SWIG wrapper: add exception mapping and enable directors feature.

---

common/schema.h
common/zmqserver.h

Add ZMQ port for orchagent.
Microsoft ADO (number only): 17753804
Orchagent need create ZMQ server for listen incoming connection.
Add ZMQ address to zmqserver.h
Add ZMQ port for orchagent.

Add ZMQ port for orchagent

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Fix collect log error in azp template

[Ci][202012] Fix collect log error in azp template

---

common/configdb.h
tests/test_redis_ut.py

This reverts commit e0f394cd44370370e872711b04a15e497b63e0f8.
The reason is unexpected behavior change of `get_entry`. ref: https://github.com/sonic-net/sonic-swss-common/pull/789#issuecomment-1639525084

Revert "Fix the issue of ignoring callback calls for removed keys. (#789)"

---

common/binaryserializer.h
tests/binary_serializer_ut.cpp

Fix binary serializer can't deserialize protopuf buffer content issue.
Microsoft ADO (number only): 17753804
Fix binary serializer can't deserialize protopuf buffer content issue.
Fix code but when deserialize binary string.
Add UT.
Pass all UT.
Fix binary serializer can't deserialize protopuf buffer content issue.

Fix binary serializer can't deserialize protopuf buffer content issue.

---

common/rediscommand.cpp
tests/Makefile.am
tests/redis_command_ut.cpp

In the previous implementation, the private member variable, len, will store the error code of redisFormat. This PR is for fixing that if the redisFormat raise an unexpected error code, the `len` will be assigned to zero.

[redisCommand]: Not store the error return code of redisFormat

---

.azure-pipelines/build-swss-template.yml
.azure-pipelines/test-docker-sonic-vs-template.yml

Swss containter needs dash_api to properly build, based on https://github.com/sonic-net/sonic-swss/pull/2722, attempting to add missing libs

[azp] Fix swss missing libs

---

Makefile.am
common/Makefile.am
configure.ac
pyext/py2/Makefile.am
pyext/py3/Makefile.am
sonic-db-cli/Makefile.am

Fix swss-common binskim errors.
Microsoft ADO (number only): 25090081
binskim scan report error BA3003, BA3004 and BA3011:
BA3003: The stack protector was not found. This may be because '--stack-protector-strong' was not used, or because it was explicitly disabled by '-fno-stack-protectors'.
BA3004: using debugging dwarf version '{1}'. The dwarf version 5 contains more information and should be used. To enable the debugging version 5 use '-gdwarf-5'.
BA3011: The BIND_NOW flag is missing from this binary, so relocation sections will not be marked as read only after the binary is loaded.  An attacker can overwrite these to redirect control flow.  Ensure you are compiling with the compiler flags '-Wl,-z,now' to address this.
Add compiler flag and ld flag according to following document: …

Fix swss-common binskim errors

---

common/Makefile.am
common/asyncdbupdater.cpp
common/asyncdbupdater.h
common/zmqconsumerstatetable.cpp
common/zmqconsumerstatetable.h
common/zmqproducerstatetable.cpp
common/zmqproducerstatetable.h
tests/zmq_state_ut.cpp

Some scenarios require sonic-gnmi side update data to APPL_DB.
Move async DB update code to AsyncDBUpdater.
Reuse AsyncDBUpdater in both ZmqProducerStateTable and ZmqConsumerStateTable
Add new UT.
Support async DB update for both ZMQ producer&consumer table.

Support async DB update for both ZMQ producer&consumer table.

---

common/asyncdbupdater.h
common/binaryserializer.h
common/zmqclient.cpp
common/zmqclient.h
common/zmqconsumerstatetable.cpp
common/zmqconsumerstatetable.h
common/zmqproducerstatetable.cpp
common/zmqproducerstatetable.h
common/zmqserver.cpp
common/zmqserver.h
tests/binary_serializer_ut.cpp
tests/zmq_state_ut.cpp

The existing batch implementation in ZmqProducerStateTable only calls the individual API repeatedly. This change brings in the real batch implementation:
1. Add a new method in ZmqProducerStateTable, send(), which can batch both SET and DEL operations in a single call.
2. Update the BinarySerializer to encode multiple SET & DEL requests in a single message. The new encoding format is the following:
* db name
* table name
* key1
* number of attrs in key1
* field
* value
* ...
* key2
* number of attrs in key2
* field
* value
* ...
3. Increase ZMQ buffer size from 4MB to 16MB.

Add batch support in ZmqProducerStateTable.

---

common/schema.h

in order to have the host_tx_ready enhancements, the table name is added to schema.h.
HLD: https://github.com/sonic-net/SONiC/pull/1453

Add STATE_TRANSCEIVER_INFO_TABLE_NAME to shcema.h

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/docker-sonic-vs/Dockerfile

DASH build chain has been moved from sonic-buildimage to its submodule sonic-dash-api. So, this PR is for revising this dependency.

[Azp]: Fix azp dash dependency

---

common/dbconnector.cpp
common/dbconnector.h
tests/main.cpp

sonic-gnmi will use swsscommon API to read database configuration, and sonic-gnmi unit test needs to reload database configuration in the same process.
Add SonicDBConfig::reset method, and sonic-gnmi unit test will use this method to clear previous database configuration.
Add SonicDBConfig::reset method

Add SonicDBConfig::reset method

---

tests/redis_ut.cpp

Fix incorrect sizeof() value in the Table.binary_data_get unit test

[tests] fix binary_data_get unit test

---

common/logger.cpp
common/logger.h

`settingThread` of `Logger` select DB change with 1000ms timeout. It causes up to 1 second wait while destroy the logger instance. The 1 second wait is not necessary and can be replaced by `SelectableEvent`
- Microsoft ADO **(number only)**:
1. Add a new member m_stopEvent with type SelectableEvent
2. `settingThread` also selects m_stopEvent
3. `settingThread` exits if m_stopEvent comes 
Manual test

Use selectable event to terminate logger thread

---

common/Makefile.am
common/configdb.h
configure.ac
debian/rules
pyext/py2/Makefile.am
pyext/py3/Makefile.am
pyext/swsscommon.i
tests/Makefile.am

libswsscommon depends on libyang deb. libyang is deprecated in bookworm. This wouldn't be a problem for buildimage because libyang is compiled from source in buildimage. 
However, this is causing a problem in upgrading one of our app-extensions to bookworm. This app-extension is built separately and not part of buildimage infra. 
Thus provide a build flag to disable compilation of libyang dependent interfaces such as DecoratorTable etc. Please note, there is no change in the default behavior
<Build with dep profile>
```
vkarri@6c5cda5d64fa:/sonic/src/sonic-swss-common$ debuild -b -us -uc -Pnopython2,noyangmod 
vkarri@6c5cda5d64fa:/sonic/src$ sudo dpkg -i libswsscommon_1.0.0_amd64.deb vkarri@6c5cda5d64fa:/sonic/src$ sudo dpkg -i python3-swsscommon_1.0.0_amd64.deb …
```

Provide build flag to disable compilation of libyang dependent interfaces

---

common/schema.h

New table definition for ASIC/SDK health event

Support ASIC/SDK health event

---

common/asyncdbupdater.cpp
common/dbconnector.cpp

Fix DBConnector and AsyncDBUpdater not use DBKey issue.
Improve code to use DBKey when clone DBConnector.
Pass all test cases.
Fix DBConnector and AsyncDBUpdater not use DBKey issue.

Fix DBConnector and AsyncDBUpdater not use DBKey issue

---

azure-pipelines.yml

Add a step to verify the build for Bookworm for amd64, armhf, and arm64.

Add Bookworm build to PR checks

---

common/schema.h

Added Banner feature related Config DB table according to HLD: https://github.com/sonic-net/SONiC/pull/1361
Added Banner table name to schema.h.

[Banner] Added BANNER_MESSAGE table to ConfigDB

---

common/schema.h

Why I did it
This PR contains code changes for providing extension to the Event Framework as specified in the https://github.com/sonic-net/SONiC/pull/1409
How I did it
Followed design specified in https://github.com/sonic-net/SONiC/pull/1409.
Add new tables for events and alarms.

Event and alarm management: Add tables for event and alarms.

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Python package requests' latest release 2.32.0 has issues with docker package.
Use old stable version 2.31.0 instead.

Use requests==2.31.0 instead of latest version to avoid test failure.

---

.azure-pipelines/build-template.yml
pyext/swsscommon.i
tests/test_redis_ut.py

Fix the issue https://github.com/sonic-net/sonic-buildimage/issues/17025 about Redis set activity
The issue reports a memory leak on the Redis set operations
1. Didn't decrease the reference count after PySequence_GetItem
2. Use the inappropriate Swig API and didn't release the string of SWIG_AsPtr_std_string
1. Refer PR: https://github.com/sonic-net/sonic-swss-common/pull/859 from @praveenraja1
2. Replace the API SWIG_AsPtr_std_string to SWIG_AsVal_std_string
To monitor there is no dramatic memory increment after a huge amount of Redis set operations.

[swig]: Fix swig template memory leak on issue 17025 

---

.azure-pipelines/build-template.yml
pyext/swsscommon.i
tests/test_redis_ut.py

Fix the issue https://github.com/sonic-net/sonic-buildimage/issues/17025 about Redis set activity
Wait PR: https://github.com/sonic-net/sonic-swss-common/pull/836 cherry-pick to 202311
The issue reports a memory leak on the Redis set operations
1. Didn't decrease the reference count after PySequence_GetItem
2. Use the inappropriate Swig API and didn't release the string of SWIG_AsPtr_std_string
1. Refer PR: https://github.com/sonic-net/sonic-swss-common/pull/859 from @praveenraja1
2. Replace the API SWIG_AsPtr_std_string to SWIG_AsVal_std_string
To monitor there is no dramatic memory increment after a huge amount of Redis set operations.

[swig]: Fix swig template memory leak on issue 17025

---

sonic-db-cli/sonic-db-cli.cpp

Described in https://github.com/sonic-net/sonic-buildimage/issues/18733 we see that swss.sh will try to access `CHASSIS_APP_DB` via `sonic-db-cli`.
If we're on a multi-asic system it will include the `-n <asic>` argument.
Having the `-n <asic>` argument causes `sonic-db-cli` to use unix sockets due to https://github.com/sonic-net/sonic-swss-common/pull/797
If we use a unix socket to try to reach the supervisor from the LC the command will fail with:
```
admin@cmp217-5:/var/log$ sudo sonic-db-cli -n asic0 CHASSIS_APP_DB keys "*"
Invalid database name input : 'CHASSIS_APP_DB'
Unable to connect to redis (unix-socket): Cannot assign requested address
```
https://github.com/sonic-net/sonic-swss-common/pull/866 fixed a similar issue with database.sh by forcing a tcp connection when accessing …

sonic-db-cli: Don't use unix socket for redis_chassis.server

---

.azure-pipelines/test-docker-sonic-vs-template.yml

sonic-swss-common pipeline requires sonic-swss's source code to build and test.
sonic-swss pipeline requires sonic-swss-common's artifact to build and test.
Temporarily skip the vstest, to get a workable swss-common build

Temporarily skip vstest

---

common/events_common.h
tests/events_common_ut.cpp

ADO: 28728116
Capturing control character in do_capture as part of eventd is difficult as control character can be delayed such that we it is not sometimes caught when initially starting capture service. (SUB -> PUB (part of zmq proxy)).
Instead of dropping the control character as part of eventd do_capture, I will drop it as part of zmq_message_read which eventd calls via events_service.
1) Check rc value of zmq_msg_recv
2) if rc == 1 (meaning 1 byte long)
3) verify it is control character, log that we received subscription messages
4) drop it such that empty event is sent (empty events are dropped by eventd)
LIBZMQ: Control character logic: https://github.com/zeromq/libzmq/blob/cbb9925a109152426e4a8a3f8f8eaeddc0516977/src/xsub.cpp#L102
Added UT to confirm, as well as should see success …

Account for control character as part of zmq_read_part

---

common/zmqclient.cpp
common/zmqclient.h
common/zmqserver.cpp
common/zmqserver.h

Orchagent failed bind to ZMQ when mgmt VRF enabled: https://github.com/sonic-net/sonic-buildimage/issues/19638
Add VRF support to ZMQ server/client.
Pass all test cases.
Add VRF support to ZMQ server/client.

Add VRF support to ZMQ server/client

---

goext/Makefile

https://github.com/sonic-net/sonic-swss-common/pull/937
PR checker is blocked by goext build
Remove go build, and keep go test to run unit test.

Fix unit test for goext

---

common/Makefile.am
common/performancetimer.cpp
common/performancetimer.h
tests/Makefile.am
tests/performancetimer_ut.cpp

What I did
Extend the `PerformanceIntervalTimer` utility in `sonic-sairedis` repo  to measure API performance.
To optimize performance of a periodically invoked function,  we not only pay attention to how long it takes to finish execution (busy time), but also care about how long it waits to get executed (idle time). The total time determines the actual throughput in the real world system.
Hence we want to see data in 3 ways:
1. `Idle` time between two calls (a gap between this start and the last end, during which the thread just waits)
2. `Busy` time of each API call (interval between this start and this end, it's the true execution time)
3. `Total` time elapsed (idle + busy)
` | <- Initial Gap -> | <- - 1st **Execution** - -> | <- 2nd Gap -> | <- - 2nd **Execution** - -> |`
`  | …

[common] add PerformanceTimer

---

common/schema.h

Added new PORT_OPERR_TABLE table in STATE_DB
This table will be updated by OA whenever port oper down notification reports [sai_port_error_status_t](https://github.com/opencomputeproject/SAI/blob/8b8fa85178383ae0a8bf1a64279934a6b3087837/inc/saiport.h#L84) errors

Added new PORT_OPERR_TABLE table in STATE_DB

---

common/c-api/consumerstatetable.cpp
common/c-api/consumerstatetable.h
common/c-api/subscriberstatetable.cpp
common/c-api/subscriberstatetable.h
common/c-api/util.h
common/c-api/zmqconsumerstatetable.cpp
common/c-api/zmqconsumerstatetable.h
tests/c_api_ut.cpp

Previously, methods like hasData/hasCachedData were exposed through the FFI, but they are only useful for swss::Select which is not exposed, so those were deleted. Methods *_getFd were added so that ffi code may select on those fds separately from swss::Select (we need this in Rust for tokio::AsyncFd). Comments were added to better explain the intended use - Either call readData with a timeout to block in place, or use getFd to select on the fd and then call readData with a zero timeout to reset the fd.

C-api: refine interface on Selectable classes

---

common/c-api/consumerstatetable.cpp
common/c-api/dbconnector.cpp
common/c-api/dbconnector.h
common/c-api/producerstatetable.cpp
common/c-api/producerstatetable.h
common/c-api/subscriberstatetable.cpp
common/c-api/util.cpp
common/c-api/util.h
common/c-api/zmqclient.cpp
common/c-api/zmqclient.h
common/c-api/zmqconsumerstatetable.cpp
common/c-api/zmqproducerstatetable.cpp
tests/c_api_ut.cpp

This introduces a couple of new FFI types, representing owned C++ strings and arrays. We use those owned strings for database values, so they do not need to be memcpy'd across ffi boundaries. This is in response to Riff's concerns that database values which hamgrd will be reading may be large and expensive to memcpy.
Partner pr to https://github.com/sonic-net/sonic-dash-ha/pull/11

C API: improve performance by not memcpy-ing string DB values across ffi boundary 

---

common/producerstatetable.cpp
common/producerstatetable.h
common/redispipeline.h
tests/redis_piped_state_ut.cpp

**What I did**
- optimize redispipeline flush performance by remove unnecessary publish commands
- add a new parameter`bool flushPub` in `producerstatetable` constructor function
- to enable/disable batch publish feature
- default value of `m_flushPub` is `false`, so no impact on existing codes
- optimization is effective only explicitly set this option
- remove individual publish command from the `producerstatetable` APIs' lua scripts
- add a publish command when the pipeline flushes [if `m_flushPub` is `true`]
**Why I did it**
- save TCP traffic and increase fpmsyncd efficiency
It's a feature included in  [BGP Loading Optimization HLD #1521](https://github.com/sonic-net/SONiC/pull/1521)  ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/Azure/SONiC/1521 …

[common] enable redispipeline to only publish after flush

---

common/c-api/zmqclient.cpp
common/zmqclient.cpp
common/zmqclient.h
common/zmqproducerstatetable.cpp
common/zmqproducerstatetable.h

Every ZmqProducerStateTable  will allocate 16MB buffer, this can be improve by share same buffer in ZmqClient.
Improve memory usage by move ZMQ serialize buffer from ZmqProducerStateTable to ZmqClient.
Pass all test cases.
Improve memory usage by move ZMQ serialize buffer from ZmqProducerStateTable to ZmqClient.

Improve memory usage by move ZMQ serialize buffer from ZmqProducerStateTable to ZmqClient

---

common/redispipeline.h

replace ";" with "\n" when concatenating multiple redis cmds

use "\n" instead of semicolon to separate redis commands in a c++ string

---

common/schema.h

Why I did it
Added a new field in `FLEX_COUNTER_TABLE` to represent the bulk chunk size and bulk chunk size per counter ID for bulk counter polling.

Add field for bulk chunk size in flex counter

---

common/c-api/consumerstatetable.cpp
common/c-api/consumerstatetable.h
common/c-api/dbconnector.cpp
common/c-api/dbconnector.h
common/c-api/producerstatetable.cpp
common/c-api/producerstatetable.h
common/c-api/result.h
common/c-api/subscriberstatetable.cpp
common/c-api/subscriberstatetable.h
common/c-api/table.cpp
common/c-api/table.h
common/c-api/util.cpp
common/c-api/util.h
common/c-api/zmqclient.cpp
common/c-api/zmqclient.h
common/c-api/zmqconsumerstatetable.cpp
common/c-api/zmqconsumerstatetable.h
common/c-api/zmqproducerstatetable.cpp
common/c-api/zmqproducerstatetable.h
common/c-api/zmqserver.cpp
common/c-api/zmqserver.h
tests/c_api_ut.cpp
tests/main.cpp

The existing C API has no mechanism for passing exceptions over the FFI border. This PR changes C API functions to return a result type indicating whether an exception occurred. Previous return values now are output via pointer arguments.
Currently this just implements the changes for DBConnector, as an easier to review demo. However, the complete change is already finished locally. I can update this PR to contain the whole change when ready.
closes https://github.com/sonic-net/sonic-swss-common/issues/932

C API Exceptions

---

common/c-api/README.md
common/c-api/util.h

Added a README for the C API at Riff's request, explaining its purpose, exception handling, and memory management practices.

c-api: README.md

---

.azure-pipelines/build-sairedis-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml

debian mirror buster-backports are deprecated. Use ms snapshot instead.
https://backports.debian.org/news/Removal_of_buster-backports_from_the_debian_archive

[ci] Use ms snapshot in buster env.

---

.azure-pipelines/docker-sonic-vs/start.sh

Update start.sh for new sonic-swss soft bfd tests.
We have updated the agent pool of vstest to latest Ubuntu 20.04, but vstest is failing in bfd tests. Checked sonic-swss and sonic-sairedis repo and found there is a recent change, we need to update start.sh for new sonic-swss soft bfd tests
Original PR: https://github.com/sonic-net/sonic-swss/pull/3525 and https://github.com/sonic-net/sonic-sairedis/pull/1558

Update start.sh for new sonic-swss soft bfd tests

---

.github/workflows/codeql-analysis.yml

Becuase we see error message "This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101".

Update codeql runs-on ubuntu version to 22.04

---

.azure-pipelines/build-sairedis-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml

Limit grabbed libyang libraries to only v1.
Upgrading to libyang v3 (https://github.com/sonic-net/sonic-buildimage/pull/21679) is causing the swss-common pipeline build to fail. The pipeline assumes that any package starting with `libyang_` or `libyang-` is a libyang v1 package and tries to install it. However, the dev header package for libyang v3 starts with `libyang-`, so the pipeline tries to download/install it as well, which causes the build to fail since it depends on the base libyang v3 package which is not grabbed because it starts with `libyang3`.

[azp] Only grab libyang v1 libs for AZP jobs

---

common/dbconnector.cpp
common/dbconnector.h
common/rediscommand.cpp
common/rediscommand.h
tests/redis_ut.cpp

* Adding a change to delete multiple keys per one DEL operation instead of one key per DEL
Signed-off-by: Thanh sonphung@google.com

swss-common: Improve batch key delete

---

.github/workflows/prevent-cfg.yml

Add a checker to prevent adding new CFG_ macros when update common/schema.h.
CFG_XXX_TABLE_NAME macros should be auto-generated from YANG models via cfg_schema.h.
Introduced .github/workflows/prevent-cfg.yml which runs on PRs that modify common/schema.h.
It extracts all CFG_ macros defined in the file and compares them against an allowed legacy list.
- Microsoft ADO: 35075048
Manual test CFG change and other change in common/schema.h

Prevent adding new CFG table since it is auto generated
