common/consumertable.cpp
GET api channel will be used to notify syncd about init/apply view, and in this case we don't want to put data into asic DB
=> Add notify option for table consumer

common/consumerstatetable.cpp, common/consumerstatetable.h, common/consumertable.cpp, common/consumertable.h, tests/redis_state_ut.cpp
=> Implement buffered pop for ConsumerTable/ConsumerStateTable

tests/Makefile.am, tests/ipaddress_ut.cpp
Signed-off-by: Shuotian Cheng <shuche@microsoft.com>
=> [test]: Add IpAddresses empty test

tests/Makefile.am, tests/macaddress_ut.cpp
Signed-off-by: Shuotian Cheng <shuche@microsoft.com>
=> [test]: Add MacAddress test

common/macaddress.cpp, tests/macaddress_ut.cpp
=> Handle errors in parseMacString

common/ipaddresses.cpp, common/ipaddresses.h, tests/ipaddress_ut.cpp
- Check if a set of IPs is a subset of another set of IPs
=> [IpAddresses]: Add contains(IpAddresses ips) function

common/loglevel.cpp
To merge into the branch v1.0.1.
=> Fix SAI_LOG macros for SAI 1.0

common/loglevel.cpp
The current message is not align with SAI 1.0.
Replace SAI_LOG_ prefix with SAI_LOG_LEVEL_ prefix.
=> [loglevel]: Update usage messages

common/schema.h
This is to support
```
SAI_SWITCH_ATTR_FDB_UNICAST_MISS_PACKET_ACTION
SAI_SWITCH_ATTR_FDB_BROADCAST_MISS_PACKET_ACTION
SAI_SWITCH_ATTR_FDB_MULTICAST_MISS_PACKET_ACTION
```
=> [schema]: Add SWITCH_TABLE into schema

common/consumerstatetable.cpp, common/consumerstatetable.h, common/consumertable.cpp, common/consumertable.h, common/producerstatetable.cpp, common/producerstatetable.h, common/producertable.cpp, common/producertable.h, common/selectable.h, common/table.h
Introduced TableConsumable interface and let ProducerTable inherits TableBase interface.
=> Refactor Consumer*Table interface, and optimize popping

common/subscriberstatetable.cpp
Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>
=> Fix syntax in assertion

common/subscriberstatetable.cpp, common/table.cpp, common/table.h, pyext/swsscommon.i, tests/redis_piped_ut.cpp, tests/redis_ut.cpp, tests/test_redis_ut.py
also rename getTableKeys -> getKeys, getTableContent -> getContent
=> add python binding for swss::Table

common/logger.cpp, common/logger.h, common/schema.h
logging to stdout/stderr simplifies deploying sonic daemons as containers.
=> [logger] Support logging to stdout/stderr

debian/rules
=> [rules]: Clean pyext/*.py files in dh_clean

common/redispipeline.h, common/table.cpp, common/table.h, tests/redis_ut.cpp
To support get/set individual field of a key in Table class.
=> Warm reboot: Add Table::getEntry() and Table::setEntry

common/converter.h, tests/converter_ut.cpp
There are many string comparisons in the project. It is good to have
a function like this to compare between strings stored in the database
and those predefined values.
=> [converter]: Add to_upper function to convert string into uppercase

common/converter.h
=> [converter]: Make to_upper function static inline

common/producerstatetable.cpp, common/producerstatetable.h, tests/redis_piped_state_ut.cpp
…has been picked up by consumer.
=> Add ProducerStateTable::count()/clear()

common/schema.h
define FRONT_PANEL_PORT_PREFIX "Ethernet"
define PORTCHANNEL_PREFIX      "PortChannel"
define VLAN_PREFIX             "Vlan"
=> [schema]: Add port/lag/vlan prefix definitions

common/notificationproducer.cpp, common/notificationproducer.h, tests/ntf_ut.cpp
=> NotificationProducer.send() returns the number of clients that received the message

common/schema.h
Signed-off-by: Marian Pritsak <marianp@mellanox.com>
=> [schema.h]: Define STATE_VRF_TABLE_NAME

common/schema.h
New tables for VNET peering and Vxlan feature
=> VNET/VXLAN Tables

common/schema.h
key                 = MGMT_PORT_TABLE|ifname
oper_status         = "down" / "up" ; oper status
=> [schema]: Add MGMT_PORT_TABLE in state database

common/schema.h
=> Add VNET Route tables 

common/Makefile.am, common/warm_restart.cpp, common/warm_restart.h, tests/Makefile.am, tests/warm_restart_ut.cpp
=> mv WarmStart class from swss to swss-common repo

common/schema.h
=> [schema]: Add STATE_MIRROR_SESSION_TABLE_NAME

common/schema.h
=> [schema]: Add SWITCH_CAPABILITY_TABLE

common/consumer_table_pops.lua
Signed-off-by: Wenda Ni <wenni@microsoft.com>
=> White-list clear_stats op from orchagent to syncd

common/select.h
Signed-off-by: Wenda Ni <wenni@microsoft.com>
=> Correct comment

common/schema.h
=> [schema]: Remove duplicate STATE_MIRROR_SESSION_TABLE_NAME

common/consumertable.cpp, common/redisapi.h, common/selectabletimer.cpp, common/subscriberstatetable.cpp
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [Warnings] Fix all printf format specifiers for 32bit arch compilation

common/consumer_table_pops.lua
[consumer_table] Add messages for performing attribute enum value capabilities query
* Specifies a request/response message pair for sai_query_attribute_enum_values_capability
Signed-off-by: Danny Allen <daall@microsoft.com>
Related to: Azure/sonic-sairedis#525
=> [consumer_table] Add messages for performing attribute enum value capabilities query

common/logger.cpp, common/loglevel.cpp
* replacing old APIs with new APIs in swsscommon
=> [MultiDB]: apply new APIs in swss-common

common/schema.h
Schema changes per HLD:
https://github.com/Azure/SONiC/blob/master/doc/ecmp/fine_grained_next_hop_hld.md
=> [schema] Fine Grained ECMP schema changes

common/schema.h
**- Why I did it**
Defined Table name for CoPP Manager and state tables
**- How I did it**
**- How to verify it**
**- Description for the changelog**
**- A picture of a cute animal (not mandatory but encouraged)**
=> Copp Manager Changes

common/exec.cpp, common/exec.h, tests/exec_ut.cpp
Fix https://github.com/Azure/sonic-swss-common/issues/327
=> Fix swss::exec return value

common/schema.h
=> add state db entry for fgnhg route entry

pyext/swsscommon.i, tests/test_redis_ut.py
So in python, it will emulate a dict.
=> Implement FieldValueMap update method

common/redisapi.h
Fixed https://github.com/Azure/sonic-buildimage/issues/5854
=> Reduce notice logging in loadRedisScript()

README.md
* Add python3-dev and libnl-nf-3-dev as build dependencies
* Made installing Google Test a requirement for build
Signed-off-by: Alexandru Banu <Alexandru.Banu@metaswitch.com>
=> README.md: Update build requirements

README.md
=> add azure pipeline build badge

azure-pipelines.yml
=> [build]: add build check for arm64 and armhf

azure-pipelines.yml
=> [ci]: add timeout to 180 minutes for arm build

common/configdb.cpp, common/dbconnector.cpp, common/dbconnector.h, pyext/swsscommon.i, tests/test_redis_ut.py
=> Change DBConnector::hgetall return type from map to unordered_map

common/configdb.cpp, common/configdb.h, common/dbconnector.cpp, common/dbconnector.h, common/dbinterface.cpp, common/dbinterface.h, common/redisreply.cpp, common/redistran.cpp, common/redistran.h, common/sonicv2connector.cpp, common/sonicv2connector.h, tests/test_redis_ut.py
And simplify ConfigDBConnector/ConfigDBPipeConnector SWIG wrappers
Tested in unit test.
Tested `config load_minigraph` with minor code change on DUT.
=> Fix ConfigDBPipeConnector.get_config() implementation

azure-pipelines.yml
=> [ci]: build on ubuntu 20.04

common/redisclient.h, tests/redis_ut.cpp
=> Fix: RedisClient.set() should return bool

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-sairedis-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build_and_install_module.sh, .azure-pipelines/docker-sonic-vs/Dockerfile, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
=> [ci]: add vstest

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile
Signed-off-by: Danny Allen <daall@microsoft.com>
=> [azp] Purge swss before installing the newly built deb package

common/dbinterface.cpp, common/dbinterface.h, common/sonicv2connector.cpp, common/sonicv2connector.h, tests/test_redis_ut.py
Resolved https://github.com/Azure/sonic-py-swsssdk/issues/50
Add unit test.
=> [swig] Implement SonicV2Connector.hmset()

common/configdb.cpp, common/configdb.h, tests/test_redis_ut.py
Originally this property is not working.
Add unit test.
=> [swig] fix ConfigDBConnector.db_name

tests/test_redis_ut.py
To cover fix #415 
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>
=> [tests] add test to cover correct exception handling in python wrapper

common/schema.h
Refer to HLD:  https://github.com/Azure/SONiC/pull/706
=> sonic-swss-common changes for MPLS support

azure-pipelines.yml
Fix azure pipeline template branch reference error
=> [ci]: Fix azure pipeline template branch reference error

common/dbconnector.h, common/sonicv2connector.h
So it will work in both swig3.0 and swig4.0
=> Reimplement swig properties

tests/test_redis_ut.py
test_ConfigDBSubscribe has timing risk in unit test, because multiple thread is using the same ConfigDBConnector instance, and reuse Redis connection. So there are possibility to interleave Redis transaction in between.
What I did:
1. swap the role of main thread and spawned thread
2. spawned thread uses a new ConfigDBConnector instance locally constructed
=> Fix test_ConfigDBSubscribe timing risk

.azure-pipelines/build_and_install_module.sh
Fix the option missing in kernel config issue
The installing module step will hang forever before the issue fixed.
=> [ci]: Fix the option missing in kernel config issue

.azure-pipelines/build-template.yml, azure-pipelines.yml
=> [ci]: use native arm64 and armhf pool to build

common/schema.h
Added NVGRE tunnel related tables
Signed-off-by: Vadym Hlushko <vadymh@nvidia.com>
=> [nvgre] Added NVGRE tunnel related tables

azure-pipelines.yml
Update official build:
Build.SourceBranch -> Build.SourceBranchName
=> [ci] Update azure pipeline branch variable reference.

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-sairedis-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
cherry-pick PRs from master:
[[ci] Parameterize pipeline and improve azure pipeline](https://github.com/Azure/sonic-swss-common/pull/599)
[[ci] Update azure pipeline branch variable reference. ](https://github.com/Azure/sonic-swss-common/pull/611)
=> Cherry-pick PRs from master branch

.azure-pipelines/build-template.yml
Change diff coverage threshold to 80%
=> [ci]: Change diff coverage threshold to 80% 

.azure-pipelines/test-docker-sonic-vs-template.yml
Include changes to improve pytest speed. Reference from: 
https://github.com/sonic-net/sonic-swss/pull/2350
https://github.com/sonic-net/sonic-swss/pull/2390
=> Add changes to yml file to improve pytest

.azure-pipelines/build_and_install_module.sh, common/events.cpp
Change syslog level from ERR of event publish to INFO
=> Change syslog level of Event Publish

azure-pipelines.yml
Remove libboost1.71 from being installed, already include is libboost, which will take highest version
=> Remove libboost1.71-dev dep

.azure-pipelines/build-sairedis-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, azure-pipelines.yml
Use correct sonic-slave docker image as environment.
Fix build issue.
=> Fix sonic-slave docker image environment issue.

.azure-pipelines/build-sairedis-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/build_and_install_module.sh
run 'apt-get update' before 'apt-get install'
=> [ci] Fix apt-get install unable locate package issue.

.azure-pipelines/build-sairedis-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/build_and_install_module.sh, .azure-pipelines/test-docker-sonic-vs-template.yml
cherry-pick PRs:
```
7a6783b [ci] Continue on error when running test.
1b369ab [ci] Fix apt-get install unable locate package issue. (#753)
```
=> Cherry-pick PRs in master branch to unblock PR checks.

.azure-pipelines/test-docker-sonic-vs-template.yml
Unblock pipeline when running CI build and scheduled build.
=> [ci] Continue on error when running test.

.azure-pipelines/build-sairedis-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/build_and_install_module.sh, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
cherry-pick PRs:
```
7a6783b [ci] Continue on error when running test.
1b369ab [ci] Fix apt-get install unable locate package issue. (#753)
28dc42a Fix sonic-slave docker image environment issue. (#727)
```
=> Cherry-pick PRs in master branch to unblock PR checks. 

common/logger.cpp, common/logger.h, tests/logger_ut.cpp
This is to cherry-pick https://github.com/sonic-net/sonic-swss-common/pull/766 into 202205 branch.
=> [202205][logger] Add public `restartLogger` to restart logger thread

.azure-pipelines/build-template.yml, .coveragerc
[Ci] Change the code coverage to exclude the tests folder
=> [Ci] Change the code coverage to exclude the tests folder

.azure-pipelines/test-docker-sonic-vs-template.yml
Fix collect log error in azp template
=> [Ci] Fix collect log error in azp template

.azure-pipelines/build-sairedis-template.yml
Fix the sairedis build target not found issue
=> [Ci] Fix the sairedis build target not found issue

common/events_common.h, tests/events_common_ut.cpp
This reverts commit 2365fe81f14197330c2034dd8231b9dfb49016b9.
Will be creating new PR to solve issue with proper RC instead of simply dropping message.
=> Revert "Add check before deserializing messages (#812)"

common/zmqserver.cpp
Fix race condition in ZmqServer.
=> Fix race condition in ZmqServer.

common/dbconnector.cpp, common/dbconnector.h, pyext/swsscommon.i, tests/redis_multi_ns_ut.cpp, tests/test_redis_ut.py
Get a new API `getDbKeys` in dbconnector to fetch all DB keys.
=> [dbconnector]: Add API getDbKeys in dbconnector

common/schema.h
Add new table schema for BMP feature.
=> Add new table schema for BMP feature.

.azure-pipelines/test-docker-sonic-vs-template.yml
Reverts sonic-net/sonic-swss-common#891
=> Revert "Temporarily skip vstest"

.azure-pipelines/test-docker-sonic-vs-template.yml
https://github.com/sonic-net/sonic-swss/pull/3048 moves DASH-specific VS tests into a separate folder
=> [azp]Run DASH vs tests

common/consumer_table_pops.lua
Support new OPs for stats stream telemetry capability query: https://github.com/opencomputeproject/SAI/blob/d158311e4f239f0f9f8cabab073a10dbab82a848/inc/saiobject.h#L308-L319
=> [consumer_table_pops]: Support Stats ST Capability query
